import Lsc.Types

namespace Lsc.Compile.IR

/-- Flat IR: storage slots resolved, linear types erased. -/
inductive Expr where
  | lit : Nat → Expr
  | local : Ident → Expr
  | sload : Nat → Expr
  | add : Expr → Expr → Expr
  | sub : Expr → Expr → Expr
  | mul : Expr → Expr → Expr
  | div : Expr → Expr → Expr
  | lt : Expr → Expr → Expr
  | eq : Expr → Expr → Expr
  | isZero : Expr → Expr
  deriving Repr

inductive Stmt where
  | skip : Stmt
  | seq : Stmt → Stmt → Stmt
  | letBind : Ident → Expr → Stmt
  | sstore : Nat → Expr → Stmt
  | ifRevert : Expr → Stmt
  | log0 : Nat → Stmt
  | log1 : Nat → Expr → Stmt
  | revert0 : Stmt
  /-- `return e;` (`view` functions only, `Lang/AST.lean`'s `Stmt.ret`) — ABI-encodes `e`'s
      single 32-byte-word value into memory and halts with `RETURN` (`Bytecode/Codegen.lean`'s
      `.ret` case). Every supported `Ty` (`uint256`/`bool`/`address`/`wei`/`wad`) is exactly one
      32-byte word wide, so no length-prefix/dynamic-ABI encoding is needed. -/
  | ret : Expr → Stmt
  /-- A real EVM `CALL`, **safe by construction — no opt-out**: unlike a raw
      `address.call(...)`, there is no way to reach this node's generated bytecode without also
      getting the success check `iszero(success) { revert(0, 0) }` (see `Lsc/Compile/Yul.lean`'s
      `safeExternalCall` lowering) — a contract author cannot accidentally emit an unchecked
      external call through this IR, mirroring `Lsc.ContractM.PairM.exec`/`read`'s Lean-level
      `exec_never_silently_swallows_failure`/`read_never_silently_swallows_failure` guarantee
      (`Core/ContractM.lean`) one layer down, at the bytecode this eventually becomes.

      `addr`/`inOffset`/`inSize` are the callee address and the already-ABI-encoded calldata's
      memory span (`argsOffset`/`argsSize`) — this node does not itself encode a callee's
      arguments; that remains the documented, separate "real ABI-encoded calldata" follow-up
      (`docs/todo/backlog.md`'s N-contract dispatch registry item, `Lsc/Compile/Lower.lean`'s module
      docstring) `exec`/`read` still needs before this can be wired to real `lscExec`/`lscRead`
      surface syntax end-to-end.

      `checkBoolReturn` additionally decodes the returned word as a `bool` and reverts if it is
      `false` — the real ERC20 `transfer`/`transferFrom` convention, and the actual scenario
      OpenZeppelin's `SafeERC20.safeTransfer` exists to guard against (a non-compliant token
      returning `false` instead of reverting). A callee that returns *no* data at all (`0`-length
      `RETURNDATA`) is treated as success either way — the other half of `safeTransfer`'s
      compatibility shim, for tokens that omit the return value entirely. -/
  | safeExternalCall (addr inOffset inSize : Expr) (checkBoolReturn : Bool) : Stmt
  deriving Repr

end Lsc.Compile.IR
