import Lsc.Compile.Bytecode.Contract
import Lsc.Compile.IR.WordEvalLemmas
import Lsc.Lib.Math.BytecodeProofs
import Lsc.Lib.Math.SqrtCorrect
import Lsc.Lib.Math.WordLowerProofs
import Lsc.Lib.Math.Stmt
import Mathlib.Data.Nat.Sqrt

/-!
# Compositional EVM theorem for `sqrtProductExpr`

This file names the exact unoptimized view IR consumed by production codegen.  Its proofs keep the
ABI prologue and the shared sqrt builder abstract; in particular, they never expand the builder's
twenty-two bindings.
-/

namespace Lsc.Math.EvmProofs

open Lsc
open Lsc.Compile
open Lsc.Compile.IR
open Lsc.Compile.IR.Builder
open Lsc.Compile.Bytecode

def scale : Nat := 10 ^ 18

def roundedExpr : IR.Expr :=
  .div
    (.add (.mul (.local "a") (.local "b")) (.div (.lit scale) (.lit 2)))
    (.lit scale)

def widenedExpr : IR.Expr := .mul roundedExpr (.lit scale)

def sqrtProductFresh : Fresh := { used := ["a", "b"] }

def sqrtProductBody : IR.Stmt :=
  let result := Lsc.Fixed.IRExpand.sqrtBinds widenedExpr
    ({ fresh := sqrtProductFresh } : Build)
  result.1.finish (.ret result.2)

def sqrtProductProgram : IR.Stmt :=
  .seq (.letBind "a" (.calldataWord 4))
    (.seq (.letBind "b" (.calldataWord 36)) sqrtProductBody)

/-- Canonical `FunctionDef` generated by production's `library_view sqrtProduct`. -/
def sqrtProductFunction : FunctionDef :=
  { name := "sqrtProduct"
    kind := .view
    params := [("a", .wad), ("b", .wad)]
    retTy := .wad
    body := .ret ⟨.wad,
      Stmt.sqrtProductExpr (Lsc.Fixed.Expr.var "a") (Lsc.Fixed.Expr.var "b")⟩ }

/-- Transparent lowering identity for the exact production function body and ABI offsets. -/
theorem lower_function_eq (cfg : Config) :
    Lower.function cfg sqrtProductFunction = .ok sqrtProductProgram := by
  have hbody : Lower.stmt cfg sqrtProductFunction.body = .ok sqrtProductBody := by
    rw [show sqrtProductFunction.body =
      .ret ⟨.wad, Stmt.sqrtProductExpr
        (Lsc.Fixed.Expr.var "a") (Lsc.Fixed.Expr.var "b")⟩ from rfl]
    rw [Lower.stmt_ret_wad]
    simpa [Stmt.sqrtProductExpr, Stmt.sqrtDownWad, Stmt.mulHalfUpWad, Stmt.wadScale,
      sqrtProductBody, widenedExpr, roundedExpr, scale, sqrtProductFresh] using
      (Lsc.Fixed.lowerRetStmt_sqrtProduct cfg.storage.fieldSlot
        cfg.storage.mapFieldSlot "a" "b")
  simp only [Lower.function, hbody, bind, Except.bind]
  rw [show sqrtProductFunction.params = [("a", .wad), ("b", .wad)] from rfl]
  rw [Lower.paramPrologue_two]
  rfl

/-- View codegen consumes that exact statement; no optimizer transport is involved. -/
theorem codegenInput_eq (cfg : Config) :
    (Lower.function cfg sqrtProductFunction).map
        (Bytecode.Contract.codegenInput sqrtProductFunction) =
      .ok sqrtProductProgram := by
  rw [lower_function_eq]
  rfl

def ctxA : Ctx :=
  { ({} : Ctx) with stackDepth := 1 }.bindLocal "a" (some (.calldataWord 4))

def ctxAB : Ctx :=
  ({ ctxA with stackDepth := ctxA.stackDepth + 1 }).bindLocal
    "b" (some (.calldataWord 36))

private theorem pushWidth_scale_le : pushWidth scale ≤ 32 := by decide
private theorem pushWidth_half_scale_le : pushWidth (scale / 2) ≤ 32 := by decide
private theorem pushWidth_two_le : pushWidth 2 ≤ 32 := by decide
private theorem pushWidth_four_le : pushWidth 4 ≤ 32 := by decide
private theorem pushWidth_thirtysix_le : pushWidth 36 ≤ 32 := by decide

private theorem viewValue_lit (word : WordState) (n : Nat) (hwidth : pushWidth n ≤ 32) :
    BuilderViewValue ({ fresh := sqrtProductFresh } : Build) ctxAB word (.lit n) (.ofNat n) := by
  constructor
  · exact (nameFreshnessInvariant {}).lit _ n
  · simpa [ReloadableViewExpr] using hwidth
  · rfl

private theorem viewValue_add {word a b x y}
    (ha : BuilderViewValue ({ fresh := sqrtProductFresh } : Build) ctxAB word a x)
    (hb : BuilderViewValue ({ fresh := sqrtProductFresh } : Build) ctxAB word b y) :
    BuilderViewValue ({ fresh := sqrtProductFresh } : Build) ctxAB word (.add a b)
      (EvmYul.UInt256.add x y) := by
  constructor
  · exact (nameFreshnessInvariant {}).add ha.nameSafe hb.nameSafe
  · simpa [ReloadableViewExpr] using And.intro ha.reloadable hb.reloadable
  · simp [evalExprWord, ha.eval, hb.eval]

private theorem viewValue_mul {word a b x y}
    (ha : BuilderViewValue ({ fresh := sqrtProductFresh } : Build) ctxAB word a x)
    (hb : BuilderViewValue ({ fresh := sqrtProductFresh } : Build) ctxAB word b y) :
    BuilderViewValue ({ fresh := sqrtProductFresh } : Build) ctxAB word (.mul a b)
      (EvmYul.UInt256.mul x y) := by
  constructor
  · exact (nameFreshnessInvariant {}).mul ha.nameSafe hb.nameSafe
  · simpa [ReloadableViewExpr] using And.intro ha.reloadable hb.reloadable
  · simp [evalExprWord, ha.eval, hb.eval]

private theorem viewValue_div {word a b x y}
    (ha : BuilderViewValue ({ fresh := sqrtProductFresh } : Build) ctxAB word a x)
    (hb : BuilderViewValue ({ fresh := sqrtProductFresh } : Build) ctxAB word b y) :
    BuilderViewValue ({ fresh := sqrtProductFresh } : Build) ctxAB word (.div a b)
      (EvmYul.UInt256.div x y) := by
  constructor
  · exact (nameFreshnessInvariant {}).div ha.nameSafe hb.nameSafe
  · simpa [ReloadableViewExpr] using And.intro ha.reloadable hb.reloadable
  · simp [evalExprWord, ha.eval, hb.eval]

private theorem viewValue_local_a (word : WordState) (a b : EvmYul.UInt256)
    (ha : word.calldata 4 = a) :
    BuilderViewValue ({ fresh := sqrtProductFresh } : Build) ctxAB
      ((word.setLocal "a" a).setLocal "b" b) (.local "a") a := by
  constructor
  · intro name hmem
    simp [freeVarsExpr, List.mem_singleton] at hmem
    subst name
    simp [sqrtProductFresh]
  · simp only [ReloadableViewExpr, ctxAB, ctxA, Ctx.bindLocal, Ctx.lookupBinding]
    refine ⟨by simp [ne_comm], ?_⟩
    refine ⟨{ absPos := 1, src := some (.calldataWord 4) }, .calldataWord 4, ?_, ?_, ?_⟩
    · simp [Ctx.lookupBinding, ctxAB, ctxA]
    · rfl
    · exact ⟨by simp [evalExprWord, WordState.lookupLocal, WordState.setLocal, ha],
        by simpa [ReloadableViewExpr] using pushWidth_four_le⟩
  · simp [evalExprWord, WordState.lookupLocal, WordState.setLocal]

private theorem viewValue_local_b (word : WordState) (a b : EvmYul.UInt256)
    (hb : word.calldata 36 = b) :
    BuilderViewValue ({ fresh := sqrtProductFresh } : Build) ctxAB
      ((word.setLocal "a" a).setLocal "b" b) (.local "b") b := by
  constructor
  · intro name hmem
    simp [freeVarsExpr, List.mem_singleton] at hmem
    subst name
    simp [sqrtProductFresh]
  · simp only [ReloadableViewExpr, ctxAB, ctxA, Ctx.bindLocal, Ctx.lookupBinding]
    refine ⟨by simp [ne_comm], ?_⟩
    refine ⟨{ absPos := 2, src := some (.calldataWord 36) }, .calldataWord 36, ?_, ?_, ?_⟩
    · simp [Ctx.lookupBinding, ctxAB, ctxA]
    · rfl
    · exact ⟨by simp [evalExprWord, WordState.lookupLocal, WordState.setLocal, hb],
        by simpa [ReloadableViewExpr] using pushWidth_thirtysix_le⟩
  · simp [evalExprWord, WordState.lookupLocal, WordState.setLocal]

theorem widenedExpr_viewValue (word : WordState) (a b widenedWord : EvmYul.UInt256)
    (ha : word.calldata 4 = a) (hb : word.calldata 36 = b)
    (hwidenedEval : evalExprWord
      ((word.setLocal "a" a).setLocal "b" b) widenedExpr = some widenedWord) :
    BuilderViewValue ({ fresh := sqrtProductFresh } : Build) ctxAB
      ((word.setLocal "a" a).setLocal "b" b) widenedExpr widenedWord := by
  let wordAB := (word.setLocal "a" a).setLocal "b" b
  let halfUp := viewValue_div (viewValue_lit wordAB scale pushWidth_scale_le)
    (viewValue_lit wordAB 2 pushWidth_two_le)
  let product := viewValue_mul (viewValue_local_a word a b ha) (viewValue_local_b word a b hb)
  let rounded := viewValue_div (viewValue_add product halfUp)
    (viewValue_lit wordAB scale pushWidth_scale_le)
  exact {
    (viewValue_mul rounded (viewValue_lit wordAB scale pushWidth_scale_le)) with
    eval := hwidenedEval }

private theorem viewProgram_evalStmtWord
    {word : WordState} {program : IR.Stmt} {value : EWord}
    (h : ViewProgram word program value) (hhalt : word.halt = .running) :
    ∃ final, evalStmtWord word program = some final ∧ final.halt = .returned value := by
  induction h with
  | ret word e value _ heval =>
      exact ⟨{ word with halt := .returned value }, by simp [evalStmtWord, heval], rfl⟩
  | letSeq word name e bound rest value _ heval _ ih =>
      obtain ⟨final, hfinal, hfinalHalt⟩ :=
        ih (by simpa [WordState.setLocal] using hhalt)
      refine ⟨final, ?_, hfinalHalt⟩
      have hlet : evalStmtWord word (.letBind name e) =
          some (word.setLocal name bound) := by
        simp [evalStmtWord, heval]
      rw [evalStmtWord, hlet]
      simp [show (word.setLocal name bound).halt = .running by
        simpa [WordState.setLocal] using hhalt, hfinal]

private theorem calldataBindSafe_empty (word : WordState) :
    BindReloadSafe ({ ({} : Ctx) with stackDepth := 1 }) word "a"
      (word.calldata 4) (.calldataWord 4) := by
  constructor
  · rfl
  · rfl
  · intro queried binding source hlookup
    simp [Ctx.lookupBinding] at hlookup
  · simp [ReloadableViewExpr]
    decide
  · intro queried binding source hlookup
    simp [Ctx.lookupBinding] at hlookup

private theorem calldataBindSafe_afterA (word : WordState) :
    BindReloadSafe ({ ctxA with stackDepth := ctxA.stackDepth + 1 })
      (word.setLocal "a" (word.calldata 4)) "b" (word.calldata 36)
      (.calldataWord 36) := by
  constructor
  · rfl
  · rfl
  · intro queried binding source hlookup hsource
    simp [ctxA, Ctx.bindLocal, Ctx.lookupBinding] at hlookup
    rcases hlookup with ⟨rfl, hbinding⟩
    cases hbinding
    simp only [Option.some.injEq] at hsource
    subst source
    rfl
  · simp [ReloadableViewExpr]
    decide
  · intro queried binding source hlookup hsource _
    simp [ctxA, Ctx.bindLocal, Ctx.lookupBinding] at hlookup
    rcases hlookup with ⟨rfl, hbinding⟩
    cases hbinding
    simp only [Option.some.injEq] at hsource
    subst source
    simp [ReloadableViewExpr]
    decide

private theorem seededInvariant_ctxAB (word : WordState) :
    BuilderBindingInvariant ctxAB word
      ({ fresh := sqrtProductFresh } : Build) ctxAB word := by
  constructor
  · exact BindingTrace.nil _ _
  · intro queried binding source hlookup hsource
    by_cases hb : queried = "b"
    · subst queried
      simp [ctxAB, ctxA, Ctx.bindLocal, Ctx.lookupBinding] at hlookup
      subst binding
      simp only [Option.some.injEq] at hsource
      subst source
      simp [NameSafe, freeVarsExpr]
    · by_cases ha : queried = "a"
      · subst queried
        simp [ctxAB, ctxA, Ctx.bindLocal, Ctx.lookupBinding] at hlookup
        subst binding
        simp only [Option.some.injEq] at hsource
        subst source
        simp [NameSafe, freeVarsExpr]
      · simp [ctxAB, ctxA, Ctx.bindLocal, Ctx.lookupBinding] at hlookup
        rcases hlookup with ⟨_, hbad | hbad⟩
        · exact (hb hbad.1.symm).elim
        · exact (ha hbad.2.1.symm).elim

  · intro queried binding source hlookup hsource
    by_cases hb : queried = "b"
    · subst queried
      simp [ctxAB, ctxA, Ctx.bindLocal, Ctx.lookupBinding] at hlookup
      subst binding
      simp only [Option.some.injEq] at hsource
      subst source
      simp [ctxAB, ctxA, Ctx.bindLocal, ReloadableViewExpr]
      decide
    · by_cases ha : queried = "a"
      · subst queried
        simp [ctxAB, ctxA, Ctx.bindLocal, Ctx.lookupBinding] at hlookup
        subst binding
        simp only [Option.some.injEq] at hsource
        subst source
        simp [ctxAB, ctxA, Ctx.bindLocal, ReloadableViewExpr]
        decide
      · simp [ctxAB, ctxA, Ctx.bindLocal, Ctx.lookupBinding] at hlookup
        rcases hlookup with ⟨_, hbad | hbad⟩
        · exact (hb hbad.1.symm).elim
        · exact (ha hbad.2.1.symm).elim

theorem sqrtProductBody_viewProgram
    (word : WordState) (widenedWord : EWord)
    (hinput : BuilderViewValue ({ fresh := sqrtProductFresh } : Build)
      ctxAB word widenedExpr widenedWord) :
    ∃ returned,
      ViewProgram word sqrtProductBody returned ∧
      ViewProgramReloadSafe ctxAB word sqrtProductBody := by
  change ∃ returned,
    ViewProgram word
      (Builder.seqLets
        (Lsc.Fixed.IRExpand.sqrtBinds widenedExpr
          ({ fresh := sqrtProductFresh } : Build)).1.binds
        (.ret (Lsc.Fixed.IRExpand.sqrtBinds widenedExpr
          ({ fresh := sqrtProductFresh } : Build)).2)) returned ∧
    ViewProgramReloadSafe ctxAB word
      (Builder.seqLets
        (Lsc.Fixed.IRExpand.sqrtBinds widenedExpr
          ({ fresh := sqrtProductFresh } : Build)).1.binds
        (.ret (Lsc.Fixed.IRExpand.sqrtBinds widenedExpr
          ({ fresh := sqrtProductFresh } : Build)).2))
  exact BytecodeProofs.sqrtBinds_seeded_viewProgram ctxAB word sqrtProductFresh
    widenedExpr widenedWord (seededInvariant_ctxAB word) hinput

theorem sqrtProductBody_returned_toNat
    (nat : IRState) (word : WordState) (returned : EWord)
    (hst : word.Agrees nat) (hhalt : word.halt = .running)
    (hnw : StmtNoWrap { state := nat } sqrtProductBody)
    (hview : ViewProgram word sqrtProductBody returned)
    (hbound : evalExpr nat widenedExpr < 2 ^ 256) :
    returned.toNat = Nat.sqrt (evalExpr nat widenedExpr) := by
  generalize hbuild :
    Lsc.Fixed.IRExpand.sqrtBinds widenedExpr
      ({ fresh := sqrtProductFresh } : Build) = result
  rcases result with ⟨build, resultExpr⟩
  have hbodyEq : sqrtProductBody = build.finish (.ret resultExpr) := by
    rw [sqrtProductBody, hbuild]
  obtain ⟨wordResult, semanticValue, hwordResult, hreturned, hsemantic⟩ :=
    WordLowerProofs.eval_sqrtBinds_seeded_word nat word sqrtProductFresh
      widenedExpr build resultExpr hbuild
      (by simp [NameSafe, sqrtProductFresh, widenedExpr, roundedExpr, freeVarsExpr])
      hst hhalt (by rw [← hbodyEq]; exact hnw)
  obtain ⟨viewResult, hviewResult, hviewReturned⟩ :=
    viewProgram_evalStmtWord hview hhalt
  have hstates : viewResult = wordResult := by
    rw [← hbodyEq] at hwordResult
    rw [hviewResult] at hwordResult
    exact Option.some.inj hwordResult
  subst viewResult
  rw [hreturned] at hviewReturned
  have hvalue : returned = semanticValue := Halt.returned.inj hviewReturned.symm
  rw [hvalue, hsemantic]
  exact Lsc.Math.SqrtCorrect.sqrtNat_eq_natSqrt_u256 _ hbound

/-- Compose the two ABI calldata bindings with the seeded sqrt body, using only the
`ViewProgram` and reload-safety constructors. -/
theorem sqrtProductProgram_of_body
    (word : WordState) (returned : EWord)
    (hbodyView :
      let wordAB :=
        (word.setLocal "a" (word.calldata 4)).setLocal "b" (word.calldata 36)
      ViewProgram wordAB sqrtProductBody returned)
    (hbodyReload :
      let wordAB :=
        (word.setLocal "a" (word.calldata 4)).setLocal "b" (word.calldata 36)
      ViewProgramReloadSafe ctxAB wordAB sqrtProductBody) :
    ViewProgram word sqrtProductProgram returned ∧
      ViewProgramReloadSafe ({} : Ctx) word sqrtProductProgram := by
  let wordA := word.setLocal "a" (word.calldata 4)
  let wordAB := wordA.setLocal "b" (word.calldata 36)
  change ViewProgram wordAB sqrtProductBody returned at hbodyView
  change ViewProgramReloadSafe ctxAB wordAB sqrtProductBody at hbodyReload
  constructor
  · exact
    ViewProgram.letSeq _ _ _ _ _ _ (by simp [ViewExpr]; decide) rfl <|
      ViewProgram.letSeq _ _ _ _ _ _ (by simp [ViewExpr]; decide) rfl hbodyView
  · exact ViewProgramReloadSafe.letSeq _ _ _ _ _ _
      (calldataBindSafe_empty word) <|
      ViewProgramReloadSafe.letSeq _ _ _ _ _ _
        (calldataBindSafe_afterA word) hbodyReload

/-- Under the exact dynamic no-wrap predicate, the seeded body returns floor square root.  The
`hbound` premise is the explicit u256 bound on `widened`. -/
theorem sqrtProductBody_floor
    (nat : IRState) (word : WordState) (returned : EWord)
    (hst : word.Agrees nat) (hhalt : word.halt = .running)
    (hnw : StmtNoWrap { state := nat } sqrtProductBody)
    (hview : ViewProgram word sqrtProductBody returned)
    (hbound : evalExpr nat widenedExpr < 2 ^ 256) :
    let widened := evalExpr nat widenedExpr
    returned.toNat = Nat.sqrt widened ∧
      returned.toNat * returned.toNat ≤ widened ∧
      widened < (returned.toNat + 1) * (returned.toNat + 1) := by
  dsimp only
  have hsqrt :=
    sqrtProductBody_returned_toNat nat word returned hst hhalt hnw hview hbound
  refine ⟨hsqrt, ?_, ?_⟩
  · rw [hsqrt]
    exact Nat.sqrt_le _
  · rw [hsqrt]
    exact Nat.lt_succ_sqrt _

/-- Explicit arithmetic form for the production input:
`rounded = (a*b + scale/2)/scale`, `widened = rounded*scale`.  The first two bounds are precisely
the no-wrap obligations for the multiply and rounding add; `hnw` covers the seeded sqrt trace. -/
theorem sqrtProductBody_floor_explicit
    (nat : IRState) (word : WordState) (returned : EWord) (a b : Nat)
    (ha : nat.lookupLocal "a" = a) (hb : nat.lookupLocal "b" = b)
    (hst : word.Agrees nat) (hhalt : word.halt = .running)
    (_hproduct : a * b < EvmYul.UInt256.size)
    (_hsum : a * b + scale / 2 < EvmYul.UInt256.size)
    (hnw : StmtNoWrap { state := nat } sqrtProductBody)
    (hwidened :
      let rounded := (a * b + scale / 2) / scale
      rounded * scale < 2 ^ 256)
    (hview : ViewProgram word sqrtProductBody returned) :
    let rounded := (a * b + scale / 2) / scale
    let widened := rounded * scale
    returned.toNat = Nat.sqrt widened ∧
      returned.toNat * returned.toNat ≤ widened ∧
      widened < (returned.toNat + 1) * (returned.toNat + 1) := by
  have heval : evalExpr nat widenedExpr =
      ((a * b + scale / 2) / scale) * scale := by
    simp [widenedExpr, roundedExpr, evalExpr, ha, hb]
  have hbound : evalExpr nat widenedExpr < 2 ^ 256 := by
    simpa [heval] using hwidened
  simpa [heval] using
    (sqrtProductBody_floor nat word returned hst hhalt hnw hview hbound)

private theorem calldataBindSafe_forFunction (inputCtx : Ctx) (fnName : String) (word : WordState) :
    BindReloadSafe ({ (Ctx.forFunction inputCtx fnName) with stackDepth := 1 })
      word "a" (word.calldata 4) (.calldataWord 4) := by
  constructor
  · rfl
  · rfl
  · intro queried binding source hlookup
    simp [Ctx.forFunction, Ctx.lookupBinding] at hlookup
  · simp [Ctx.forFunction, ReloadableViewExpr]
    decide
  · intro queried binding source hlookup
    simp [Ctx.forFunction, Ctx.lookupBinding] at hlookup

private def ctxA_forFunction (inputCtx : Ctx) (fnName : String) : Ctx :=
  ({ (Ctx.forFunction inputCtx fnName) with stackDepth := 1 }).bindLocal "a" (some (.calldataWord 4))

private theorem calldataBindSafe_afterA_forFunction
    (inputCtx : Ctx) (fnName : String) (word : WordState) :
    BindReloadSafe
      ({ ctxA_forFunction inputCtx fnName with
          stackDepth := (ctxA_forFunction inputCtx fnName).stackDepth + 1 })
      (word.setLocal "a" (word.calldata 4)) "b" (word.calldata 36)
      (.calldataWord 36) := by
  let ctxA' := ctxA_forFunction inputCtx fnName
  constructor
  · rfl
  · rfl
  · intro queried binding source hlookup hsource
    simp [ctxA_forFunction, Ctx.forFunction, Ctx.bindLocal, Ctx.lookupBinding] at hlookup
    rcases hlookup with ⟨rfl, hbinding⟩
    cases hbinding
    simp only [Option.some.injEq] at hsource
    subst source
    rfl
  · simp [ctxA_forFunction, Ctx.forFunction, Ctx.bindLocal, ReloadableViewExpr]
    decide
  · intro queried binding source hlookup hsource _
    simp [ctxA_forFunction, Ctx.forFunction, Ctx.bindLocal, Ctx.lookupBinding] at hlookup
    rcases hlookup with ⟨rfl, hbinding⟩
    cases hbinding
    simp only [Option.some.injEq] at hsource
    subst source
    simp [ctxA_forFunction, Ctx.forFunction, Ctx.bindLocal, ReloadableViewExpr]
    decide

private theorem ctxAfterForFunctionCalldata_locals_stack (inputCtx : Ctx) :
    let ctxA' := ctxA_forFunction inputCtx sqrtProductFunction.name
    let innerCtx := ({ ctxA' with stackDepth := ctxA'.stackDepth + 1 }).bindLocal "b" (some (.calldataWord 36))
    innerCtx.locals = ctxAB.locals ∧ innerCtx.stackDepth = ctxAB.stackDepth := by
  simp [ctxA_forFunction, ctxA, ctxAB, Ctx.forFunction, Ctx.bindLocal]

private theorem ctx_ext_locals_stack (c c' : Ctx)
    (hloc : c.locals = c'.locals) (hstack : c.stackDepth = c'.stackDepth) :
    c' = { c with labelCounter := c'.labelCounter, labelPrefix := c'.labelPrefix } := by
  cases c <;> cases c' <;> simp_all

private theorem BindReloadSafe_label_irrel (ctx : Ctx) (labelCounter : Nat) (labelPrefix : String)
    (word : WordState) (name : String) (bound : EWord) (source : IR.Expr)
    (h : BindReloadSafe ({ ctx with stackDepth := ctx.stackDepth + 1 }) word name bound source) :
    BindReloadSafe
      ({ ({ ctx with stackDepth := ctx.stackDepth + 1 }) with
          labelCounter := labelCounter, labelPrefix := labelPrefix })
      word name bound source := by
  constructor
  · exact h.sourceStable
  · exact h.sourceValue
  · exact h.oldValues
  · simpa [Ctx.bindLocal] using h.sourcePlan
  · exact h.oldPlans

private def viewReloadMeasure : IR.Stmt → Nat
  | .seq _ rest => Nat.succ (viewReloadMeasure rest)
  | _ => 0

private theorem viewReloadMeasure_lt_seq (name : String) (e : IR.Expr) (rest : IR.Stmt) :
    viewReloadMeasure rest < viewReloadMeasure (IR.Stmt.seq (IR.Stmt.letBind name e) rest) := by
  simp [viewReloadMeasure, IR.Stmt]

private theorem ViewProgramReloadSafe_label_irrel_go (labelCounter : Nat) (labelPrefix : String)
    (program : IR.Stmt) (ctx : Ctx) (word : WordState)
    (h : ViewProgramReloadSafe ctx word program) :
    ViewProgramReloadSafe { ctx with labelCounter := labelCounter, labelPrefix := labelPrefix } word program := by
  match h with
  | .ret _ _ _ =>
      exact ViewProgramReloadSafe.ret _ _ _
  | .letSeq ctx' word' bindName e bound rest hsafe hrest =>
      have hrest' := ViewProgramReloadSafe_label_irrel_go labelCounter labelPrefix rest
        (({ ctx' with stackDepth := ctx'.stackDepth + 1 }).bindLocal bindName (some e))
        (word'.setLocal bindName bound) hrest
      exact ViewProgramReloadSafe.letSeq
        ({ ctx' with labelCounter := labelCounter, labelPrefix := labelPrefix })
        word' bindName e bound rest
        (BindReloadSafe_label_irrel ctx' labelCounter labelPrefix word' bindName bound e hsafe)
        hrest'
  termination_by viewReloadMeasure program
  decreasing_by
    simp [viewReloadMeasure, IR.Stmt]

private theorem ViewProgramReloadSafe_label_irrel (ctx : Ctx) (labelCounter : Nat) (labelPrefix : String)
    (word : WordState) (program : IR.Stmt)
    (h : ViewProgramReloadSafe ctx word program) :
    ViewProgramReloadSafe { ctx with labelCounter := labelCounter, labelPrefix := labelPrefix } word program :=
  ViewProgramReloadSafe_label_irrel_go labelCounter labelPrefix program ctx word h

private theorem ViewProgramReloadSafe_locals_stack
    (ctx ctx' : Ctx) (word : WordState) (program : IR.Stmt)
    (hloc : ctx.locals = ctx'.locals) (hstack : ctx.stackDepth = ctx'.stackDepth)
    (h : ViewProgramReloadSafe ctx word program) :
    ViewProgramReloadSafe ctx' word program := by
  have hctx' : ctx' = { ctx with labelCounter := ctx'.labelCounter, labelPrefix := ctx'.labelPrefix } :=
    ctx_ext_locals_stack ctx ctx' hloc hstack
  rw [hctx']
  exact ViewProgramReloadSafe_label_irrel ctx ctx'.labelCounter ctx'.labelPrefix word program h

/-- Transport reload safety from the empty top-level context to the per-function codegen context
used by production `Codegen.stmt`. -/
theorem sqrtProductProgram_forFunction_reload
    (inputCtx : Ctx) (word : WordState)
    (hbodyReload :
      let wordAB :=
        (word.setLocal "a" (word.calldata 4)).setLocal "b" (word.calldata 36)
      ViewProgramReloadSafe ctxAB wordAB sqrtProductBody) :
    ViewProgramReloadSafe (Ctx.forFunction inputCtx sqrtProductFunction.name) word
      sqrtProductProgram := by
  let wordA := word.setLocal "a" (word.calldata 4)
  let wordAB := wordA.setLocal "b" (word.calldata 36)
  change ViewProgramReloadSafe ctxAB wordAB sqrtProductBody at hbodyReload
  let ctxA' := ctxA_forFunction inputCtx sqrtProductFunction.name
  let innerCtx := ({ ctxA' with stackDepth := ctxA'.stackDepth + 1 }).bindLocal "b" (some (.calldataWord 36))
  have hbodyReload' : ViewProgramReloadSafe innerCtx wordAB sqrtProductBody := by
    have hfields := ctxAfterForFunctionCalldata_locals_stack inputCtx
    rcases hfields with ⟨hloc, hstack⟩
    exact ViewProgramReloadSafe_locals_stack ctxAB innerCtx wordAB sqrtProductBody hloc hstack hbodyReload
  exact
    ViewProgramReloadSafe.letSeq _ _ _ _ _ _
      (calldataBindSafe_forFunction inputCtx sqrtProductFunction.name word) <|
      ViewProgramReloadSafe.letSeq _ _ _ _ _ _
        (calldataBindSafe_afterA_forFunction inputCtx sqrtProductFunction.name word) hbodyReload'

end Lsc.Math.EvmProofs
