import Escrow

/-!
Proof machinery backing `EscrowTheorem.lean` (the required `Escrow` theorems,
`docs/reference/ESCROW.md`) — kept in its own file so that file can be read as a clean
statement-of-facts document, same split as `examples/interest/test/InterestProofs.lean`/
`InterestTheorems.lean`.

`release`'s whole body elaborates to a `PairM EscrowStorage Token.TokenStorage EscrowEvent
EscrowError Unit`-valued term (see `Escrow.lean`'s module docstring): a `require` segment, then
a real black-box `PairM.exec` call into `Token.transferTyped`, then a segment that bumps
`Escrow`'s own `released` bookkeeping and emits `Released`. `runReleaseOk` below characterizes
the whole thing compositionally — `PairM.bind_apply`/`PairM.liftCaller_apply` for the two
ordinary segments, `PairM.exec_unlocked_ok`/`exec_locked` plus `runTransferOk` (`Token`'s own
characterization lemma) for the cross-contract step — rather than re-deriving `Token`'s
internals directly inside this proof, respecting the same black-box `exec` model
`docs/reference/ESCROW.md` documents. -/

open Lsc Escrow

/-! ## Generic state builders -/

def mkEscrowState (owner : Address) (released : Token.Amount)
    (caller : Address := owner) (locked : Bool := false) : ContractState EscrowStorage :=
  { storage := { owner := owner, released := released }
    context := { caller := caller, callvalue := 0, timestamp := 0, origin := 0 }
    locked := locked }

/-- `PairM.exec` doesn't rewrite the callee's `TxContext` at all (see that primitive's
docstring) — a real EVM `CALL` sets the callee's `msg.sender` to the *calling contract's own*
address, so `escrowAddr` here plays the role of "`Escrow`'s own on-chain address, as `Token`
would see it as `msg.sender`" (and is exactly whose `Token` balance `release` moves funds out
of — mirroring a real escrow contract that holds the tokens itself and calls `transfer` on its
own behalf to release them). -/
def mkTokenState (owner escrowAddr : Address) (balances : Address → Wad)
    (totalSupply : Token.Amount := ⟨0⟩) : ContractState Token.TokenStorage :=
  { storage := { owner := owner, totalSupply := totalSupply, balances := balances }
    context := { caller := escrowAddr, callvalue := 0, timestamp := 0, origin := 0 }
    locked := false }

/-! ## `WadMap` update lemmas

`TokenStorage.setMapField`/`getMapField` (generated by `deriving ContractStorage`,
`Lang/Derive.lean`) model `balances` as the total function `fun a' => if a' == a then v else
s.balances a'` — these two lemmas unlock `∀ a : Address` pointwise reasoning about it. -/

theorem setMapField_balances_at (k : Address) (v : Wad) (s : Token.TokenStorage) :
    (Token.TokenStorage.setMapField "balances" k v s).balances k = v := by
  simp [Token.TokenStorage.setMapField]

theorem setMapField_balances_ne (a k : Address) (v : Wad) (s : Token.TokenStorage)
    (h : a ≠ k) :
    (Token.TokenStorage.setMapField "balances" k v s).balances a = s.balances a := by
  simp [Token.TokenStorage.setMapField, h]

/-! ## `Token.transferTyped` — callee characterization -/

/-- The exact outcome of `exec Token.transfer(recipient, amount);` (i.e. `Token.transferTyped`,
`transfer`'s cross-contract-callable companion, `Lang/Syntax.lean`'s `resolveExecReadCallee`)
against any `Token` state, for **every** address `a` at once — the single pointwise law
`WadMap`'s total-function model calls for, in place of separate debit/credit/preservation
lemmas. The `a == sender && a == recipient` branch (checked first) is what makes this correct
even for a degenerate self-transfer (`sender = recipient`): `transfer`'s two `mapSet`s run
*sequentially*, so a self-transfer's checked-subtract and checked-add cancel out exactly,
leaving that address's balance unchanged — not "subtracted only", which a naïve
non-sequential `if a == sender then .. else if a == recipient then ..` would wrongly give. -/
theorem runTransferOk (recipient sender : Address) (amount : Token.Amount)
    (ts : ContractState Token.TokenStorage)
    (hsub : amount.n ≤ (ts.storage.balances sender).n)
    (hadd : (ts.storage.balances recipient).n + amount.n < 2 ^ 256)
    (hcaller : ts.context.caller == sender) :
    ∃ ts' : ContractState Token.TokenStorage,
      runS (Token.transferTyped recipient amount : Token.TokenM Unit) ts =
        .ok ((), ts', [Token.TokenEvent.Transfer amount]) ∧
      ∀ a : Address,
        ts'.storage.balances a =
          if a == sender && a == recipient then
            ts.storage.balances a
          else if a == sender then
            Wad.mkNat ((ts.storage.balances sender).n - amount.n)
          else if a == recipient then
            Wad.mkNat ((ts.storage.balances recipient).n + amount.n)
          else
            ts.storage.balances a := by
  have hcaller' : ts.context.caller = sender := by simpa using hcaller
  have hltS := (ts.storage.balances sender).raw.isLt
  have hltR := (ts.storage.balances recipient).raw.isLt
  have hltA := amount.raw.isLt
  have hamountToNat : (Wad.mkNat amount.raw.toNat : Wad).raw.toNat = amount.raw.toNat := by
    simp [Wad.mkNat]
  have hamt : (⟨amount.raw⟩ : Wad.Wad).raw.toNat = amount.raw.toNat := rfl
  have hsubOk : Wad.subChecked (ts.storage.balances sender) (⟨amount.raw⟩ : Wad.Wad) =
      .ok (Wad.mkNat ((ts.storage.balances sender).n - amount.n)) := by
    apply Wad.subChecked_eq_ok_of
    rw [hamt]; unfold Wad.Fixed.n at *; omega
  by_cases hsr : sender = recipient
  · subst hsr
    have haddOk : Wad.addChecked
        (Wad.mkNat ((ts.storage.balances sender).n - amount.n))
        (⟨amount.raw⟩ : Wad.Wad) =
        .ok (Wad.mkNat (ts.storage.balances sender).n) := by
      apply Wad.addChecked_eq_ok_of
      · rw [hamt]
        unfold Wad.Fixed.n at *
        simp only [Wad.mkNat, BitVec.toNat_ofNat]
        omega
      · exact hltS
    simp only [Wad.mkNat] at haddOk
    set ts1 : Token.TokenStorage :=
      Token.TokenStorage.setMapField "balances" sender
        (Wad.mkNat (ts.storage.balances sender).n)
        (Token.TokenStorage.setMapField "balances" sender
          (Wad.mkNat ((ts.storage.balances sender).n - amount.n)) ts.storage)
      with hts1
    refine ⟨{ ts with storage := ts1 }, ?_, ?_⟩
    · rw [hts1]
      simp [Token.transferTyped, Token.transfer, Token.transferImpl, Stmt.toContractM, runS,
        Stmt.evalWith, hcaller', hsubOk, haddOk, Token.TokenStorage.getMapField, Token.TokenStorage.setMapField,
        Wad.Fixed.retag, Wad.mkNat, BitVec.ofNat_toNat, List.mapM, List.mapM.loop]
    · intro a
      rw [hts1]
      by_cases ha : a = sender
      · subst ha; simp [Token.TokenStorage.setMapField]
      · simp [ha, Token.TokenStorage.setMapField]
  · have hne : sender ≠ recipient := hsr
    have haddOk : Wad.addChecked (ts.storage.balances recipient) (⟨amount.raw⟩ : Wad.Wad) =
        .ok (Wad.mkNat ((ts.storage.balances recipient).n + amount.n)) := by
      apply Wad.addChecked_eq_ok_of
      · unfold Wad.Fixed.n at *; rw [hamt]
      · exact hadd
    set ts2 : Token.TokenStorage :=
      Token.TokenStorage.setMapField "balances" recipient
        (Wad.mkNat ((ts.storage.balances recipient).n + amount.n))
        (Token.TokenStorage.setMapField "balances" sender
          (Wad.mkNat ((ts.storage.balances sender).n - amount.n)) ts.storage)
      with hts2
    refine ⟨{ ts with storage := ts2 }, ?_, ?_⟩
    · rw [hts2]
      simp [Token.transferTyped, Token.transfer, Token.transferImpl, Stmt.toContractM, runS,
        Stmt.evalWith, hcaller', hsubOk, haddOk, Token.TokenStorage.getMapField, Token.TokenStorage.setMapField,
        Wad.Fixed.retag, Wad.mkNat, BitVec.ofNat_toNat, Ne.symm hne, List.mapM, List.mapM.loop]
    · intro a
      rw [hts2]
      by_cases ha1 : a = sender
      · subst ha1
        simp [Token.TokenStorage.setMapField, hne]
      · by_cases ha2 : a = recipient
        · subst ha2
          simp [Token.TokenStorage.setMapField, ha1]
        · simp [Token.TokenStorage.setMapField, ha1, ha2]

/-! ## `release` — caller characterization -/

/-- The exact outcome of `release recipient amount`, for every address `a` at once, threading
`runTransferOk` through `release`'s middle `exec Token.transfer(..)` segment via
`PairM.exec_unlocked_ok` — the compositional route `docs/reference/ESCROW.md`'s black-box `exec`
model calls for (see this file's module docstring). `escrowAddr` is `Escrow`'s own on-chain
address as `Token` sees it (`ts.context.caller`, per `mkTokenState`'s docstring) — the account
`release` actually debits. -/
theorem runReleaseOk (recipient escrowAddr : Address) (amount : Token.Amount)
    (es : ContractState EscrowStorage) (ts : ContractState Token.TokenStorage)
    (howner : es.context.caller == es.storage.owner)
    (hlocked : es.locked = false)
    (hreleased : es.storage.released.n + amount.n < 2 ^ 256)
    (hsub : amount.n ≤ (ts.storage.balances escrowAddr).n)
    (hadd : (ts.storage.balances recipient).n + amount.n < 2 ^ 256)
    (htokenCaller : ts.context.caller == escrowAddr) :
    ∃ es' ts' : ContractState _,
      ContractM.PairM.run (release recipient amount) es ts =
        Except.ok ((), es', ts', [EscrowEvent.Released amount]) ∧
      es'.storage.released.n = es.storage.released.n + amount.n ∧
      ∀ a : Address,
        ts'.storage.balances a =
          if a == escrowAddr && a == recipient then
            ts.storage.balances a
          else if a == escrowAddr then
            Wad.mkNat ((ts.storage.balances escrowAddr).n - amount.n)
          else if a == recipient then
            Wad.mkNat ((ts.storage.balances recipient).n + amount.n)
          else
            ts.storage.balances a := by
  obtain ⟨ts', hts', hbal⟩ := runTransferOk recipient escrowAddr amount ts hsub hadd htokenCaller
  have hexecOk :
      (ContractM.PairM.exec (S := EscrowStorage) (E := EscrowEvent) (Err := EscrowError)
          (Token.transferTyped recipient amount : Token.TokenM Unit)) es ts =
        Except.ok ((), { es with locked := false }, ts', []) :=
    ContractM.PairM.exec_unlocked_ok _ es ts hlocked _ ts' _ hts'
  have hamt : (⟨amount.raw⟩ : Wad.Wad).n = amount.n := rfl
  have haddOk : Wad.addChecked (⟨es.storage.released.raw⟩ : Wad.Wad) (⟨amount.raw⟩ : Wad.Wad) =
      .ok (Wad.mkNat (es.storage.released.n + amount.n)) := by
    apply Wad.addChecked_eq_ok_of
    · rw [hamt]
    · exact hreleased
  simp only [Wad.mkNat] at haddOk
  simp only [Stmt.toContractM, Stmt.eval] at hexecOk
  refine ⟨{ es with storage := { es.storage with released := Wad.mkNat (es.storage.released.n + amount.n) } }, ts', ?_, ?_, hbal⟩
  · simp [release, Stmt.eval, Stmt.evalWith,
      howner, hlocked, hexecOk, haddOk, EscrowStorage.getField, EscrowStorage.setField,
      Wad.Fixed.retag, Wad.mkNat, BitVec.ofNat_toNat, List.mapM, List.mapM.loop]
  · unfold Wad.Fixed.n at *; simp only [Wad.mkNat, BitVec.toNat_ofNat]
    omega
