import Mathlib.Tactic.SplitIfs
import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Lsc.Security.Wealth
import Lsc.Security.WealthTheorems
import Lsc.Security.InvariantTheorems
import Examples.Token.Spec
import Examples.Token.Proofs.Tx

set_option linter.unusedSimpArgs false

open Lsc Lsc.Security Token

attribute [local simp] Claim.ofSelf AuthPred.ofSelf

namespace Token

/-!
`Token.Fn` / `Token.entry` / `Token.spec` are generated by `lsc_contract`
(constructor excluded). No pause. `claim` / `Auth` / `Inv` live in `Spec.lean`.
-/

theorem inv_solvent (self : Address) (w : World) (h : Inv w) :
    Solvent claim holdings self w := by
  obtain ⟨H, h0, hs⟩ := h
  refine ⟨H, ?_, hs.le⟩
  intro a ha
  have hraw := congrArg Amount.raw (h0 a ha)
  simp [claim]
  exact hraw.trans (Amount.raw_ofNat 0)

/-! ### Auth reductions -/

lemma Auth_transfer (a : Address) (ctx : Ctx) (dst : Address)
    (n : Amount tokenAsset) (w : World) :
    Auth a (Call.ofCtx ctx .transfer (dst, n)) w ↔ ctx.sender = a :=
  Iff.rfl

lemma Auth_burn (a : Address) (ctx : Ctx) (n : Amount tokenAsset)
    (w : World) :
    Auth a (Call.ofCtx ctx .burn n) w ↔ ctx.sender = a :=
  Iff.rfl

lemma Auth_transferFrom (a : Address) (ctx : Ctx) (src dst : Address)
    (n : Amount tokenAsset) (w : World) :
    Auth a (Call.ofCtx ctx .transferFrom (src, dst, n)) w ↔
      src = a ∧ n ≤ w.self.allowances src ctx.sender :=
  Iff.rfl

/-! ### Sum helpers for `Inv` -/

private abbrev rawBals (bals : Address → Amount tokenAsset) : Address → Nat :=
  fun a => (bals a).raw

private theorem rawBals_update (bals : Address → Amount tokenAsset) (src : Address)
    (n : Amount tokenAsset) :
    rawBals (Function.update bals src n) =
      Function.update (rawBals bals) src n.raw := by
  funext a
  by_cases h : a = src <;> simp [rawBals, Function.update, h]

private theorem nat_sum_update_sub (H : Finset Address) (f : Address → Nat)
    {i : Address} (hi : i ∈ H) {n : Nat} (hn : n ≤ f i) :
    H.sum (Function.update f i (f i - n)) + n = H.sum f := by
  have hS := sum_update_mem H f hi (f i - n)
  have : f i - n + n = f i := Nat.sub_add_cancel hn
  omega

private theorem nat_sum_update_add (H : Finset Address) (f : Address → Nat)
    {i : Address} (hi : i ∈ H) (n : Nat) :
    H.sum (Function.update f i (f i + n)) = H.sum f + n := by
  have hS := sum_update_mem H f hi (f i + n)
  omega

private theorem sum_debit (H : Finset Address) (bals : Address → Amount tokenAsset)
    {src : Address} (hs : src ∈ H) {n : Amount tokenAsset}
    (hn : n.raw ≤ (bals src).raw) :
    H.sum (rawBals (debit bals src n)) + n.raw = H.sum (rawBals bals) := by
  unfold debit
  rw [rawBals_update, Amount.raw_sub]
  exact nat_sum_update_sub H (rawBals bals) hs hn

private theorem inv_of_transferPost (σ : Storage) (src dst : Address)
    (n : Amount tokenAsset)
    (hInv : InvStorage σ) (hn : n ≤ σ.balances src) :
    InvStorage (transferPost σ src dst n) := by
  obtain ⟨H, h0, hsum⟩ := hInv
  have hn' : n.raw ≤ (σ.balances src).raw := hn
  by_cases hsrc : src ∈ H
  · by_cases hto : dst ∈ H
    · refine ⟨H, ?_, ?_⟩
      · intro a ha
        have ha_to : a ≠ dst := by intro h; subst h; exact ha hto
        have ha_src : a ≠ src := by intro h; subst h; exact ha hsrc
        simp [transferPost, credit_other _ ha_to, debit_other _ ha_src]
        exact h0 a ha
      · have hs1 := sum_debit H σ.balances hsrc hn'
        let f := rawBals (debit σ.balances src n)
        have hsum' :
            H.sum (rawBals (Function.update (debit σ.balances src n) dst
              (debit σ.balances src n dst + n))) =
              H.sum f + n.raw := by
          rw [rawBals_update, Amount.raw_add]
          exact nat_sum_update_add H f hto n.raw
        change H.sum (rawBals (transferPost σ src dst n).balances) =
          (transferPost σ src dst n).totalSupply.raw
        simp only [transferPost, credit]
        exact (hsum'.trans hs1).trans hsum
    · have hne : src ≠ dst := by intro h; subst h; exact hto hsrc
      refine ⟨insert dst H, ?_, ?_⟩
      · intro a ha
        have hat : a ≠ dst := by
          intro h; subst h; exact ha (Finset.mem_insert_self _ _)
        have haH : a ∉ H := fun hH => ha (Finset.mem_insert_of_mem hH)
        have ha_src : a ≠ src := by intro h; subst h; exact haH hsrc
        simp [transferPost, credit_other _ hat, debit_other _ ha_src]
        exact h0 a haH
      · have hs1 := sum_debit H σ.balances hsrc hn'
        let f := rawBals (debit σ.balances src n)
        have hframe := sum_update_not_mem H f hto (f dst + n.raw)
        have hb0 : σ.balances dst = 0 := h0 dst hto
        have hdt : debit σ.balances src n dst = 0 := by
          simp [debit, Function.update_of_ne hne.symm, hb0]
        have hsum' :
            (∑ a ∈ insert dst H, rawBals (transferPost σ src dst n).balances a) =
              H.sum (rawBals σ.balances) := by
          rw [Finset.sum_insert hto]
          simp only [transferPost, credit]
          rw [rawBals_update, Amount.raw_add, Function.update_self, hframe]
          simp [hdt, Amount.raw_zero]
          rw [Nat.add_comm]
          exact hs1
        change (∑ a ∈ insert dst H,
            ((transferPost σ src dst n).balances a).raw) =
          (transferPost σ src dst n).totalSupply.raw
        simpa [transferPost] using hsum'.trans hsum
  · have hb0 : σ.balances src = 0 := h0 src hsrc
    have hn0 : n = 0 := by
      cases n with | mk nraw =>
      have hz : (σ.balances src).raw = 0 := by
        simpa [Amount.raw_zero] using congrArg Amount.raw hb0
      have : nraw = 0 := Nat.eq_zero_of_le_zero (hn'.trans_eq hz)
      subst this
      rfl
    subst hn0
    have hbals : (transferPost σ src dst 0).balances = σ.balances := by
      have hsub0 : σ.balances src - 0 = σ.balances src :=
        Amount.ext (by simp [Amount.raw_sub, Amount.raw_zero])
      have hadd0 (x : Amount tokenAsset) : x + 0 = x :=
        Amount.ext (by simp [Amount.raw_add, Amount.raw_zero])
      funext a
      simp [transferPost, credit, debit, hsub0, hadd0, Function.update_eq_self]
    refine ⟨H, fun a ha => ?_, ?_⟩
    · rw [show (transferPost σ src dst 0).balances a = σ.balances a from
        congrFun hbals a]
      exact h0 a ha
    · have hsum' :
          (∑ a ∈ H, ((transferPost σ src dst 0).balances a).raw) =
            H.sum (fun a => (σ.balances a).raw) := by
        apply Finset.sum_congr rfl
        intro a _; rw [hbals]
      simpa [transferPost] using hsum'.trans hsum

private theorem inv_of_mintPost (σ : Storage) (dst : Address) (n : Amount tokenAsset)
    (hInv : InvStorage σ) :
    InvStorage (mintPost σ dst n) := by
  obtain ⟨H, h0, hsum⟩ := hInv
  refine ⟨insert dst H, ?_, ?_⟩
  · intro a ha
    have hat : a ≠ dst := by
      intro h; subst h; exact ha (Finset.mem_insert_self _ _)
    have haH : a ∉ H := fun hH => ha (Finset.mem_insert_of_mem hH)
    simp [mintPost, credit_other _ hat]
    exact h0 a haH
  · by_cases ht : dst ∈ H
    · rw [Finset.insert_eq_of_mem ht]
      let f := rawBals σ.balances
      have hcancel :
          H.sum (rawBals (Function.update σ.balances dst (σ.balances dst + n))) =
            H.sum f + n.raw := by
        rw [rawBals_update, Amount.raw_add]
        exact nat_sum_update_add H f ht n.raw
      change H.sum (fun a => ((mintPost σ dst n).balances a).raw) =
        (mintPost σ dst n).totalSupply.raw
      simp only [mintPost, credit]
      simpa [rawBals] using hcancel.trans (by rw [hsum])
    · let f := rawBals σ.balances
      have hframe := sum_update_not_mem H f ht (f dst + n.raw)
      have hb0 : σ.balances dst = 0 := h0 dst ht
      have hsum' :
          (∑ a ∈ insert dst H, ((mintPost σ dst n).balances a).raw) =
            H.sum f + n.raw := by
        rw [Finset.sum_insert ht]
        simp only [mintPost, credit, Function.update_self]
        change (σ.balances dst + n).raw +
            H.sum (rawBals (Function.update σ.balances dst (σ.balances dst + n))) =
          H.sum f + n.raw
        rw [rawBals_update, Amount.raw_add, hb0, Amount.raw_zero, Nat.zero_add]
        have hf0 : f dst = 0 := by simpa [rawBals, Amount.raw_zero] using congrArg Amount.raw hb0
        have hfr : H.sum (Function.update f dst n.raw) = H.sum f := by
          simpa [hf0, Nat.zero_add] using hframe
        rw [hfr, Nat.add_comm]
      change (∑ a ∈ insert dst H, ((mintPost σ dst n).balances a).raw) =
        (mintPost σ dst n).totalSupply.raw
      simpa [mintPost] using hsum'.trans (by rw [hsum])

private theorem inv_of_burnPost (σ : Storage) (src : Address) (n : Amount tokenAsset)
    (hInv : InvStorage σ) (hn : n ≤ σ.balances src) :
    InvStorage (burnPost σ src n) := by
  obtain ⟨H, h0, hsum⟩ := hInv
  have hn' : n.raw ≤ (σ.balances src).raw := hn
  by_cases hs : src ∈ H
  · refine ⟨H, ?_, ?_⟩
    · intro a ha
      have ha_src : a ≠ src := by intro h; subst h; exact ha hs
      simp [burnPost, debit_other _ ha_src]
      exact h0 a ha
    · have hs1 := sum_debit H σ.balances hs hn'
      have hsumd :
          H.sum (rawBals (debit σ.balances src n)) =
            H.sum (rawBals σ.balances) - n.raw := by
        rw [← Nat.add_sub_cancel (H.sum (rawBals (debit σ.balances src n))) n.raw, hs1]
      change H.sum (fun a => ((burnPost σ src n).balances a).raw) =
        (burnPost σ src n).totalSupply.raw
      simp only [burnPost, debit, Amount.raw_sub]
      simpa [rawBals] using hsumd.trans (by rw [hsum])
  · have hb0 : σ.balances src = 0 := h0 src hs
    have hn0 : n = 0 := by
      cases n with | mk nraw =>
      have hz : (σ.balances src).raw = 0 := by
        simpa [Amount.raw_zero] using congrArg Amount.raw hb0
      have : nraw = 0 := Nat.eq_zero_of_le_zero (hn'.trans_eq hz)
      subst this
      rfl
    subst hn0
    have hbals0 : σ.balances src - 0 = σ.balances src := Amount.ext (by simp [Amount.raw_sub])
    refine ⟨H, ?_, ?_⟩
    · intro a ha
      simp [burnPost, debit, hbals0, Function.update_eq_self]
      exact h0 a ha
    · simpa [burnPost, debit, hbals0, Function.update_eq_self, Amount.raw_zero, Amount.raw_sub,
        Nat.sub_zero] using hsum

/-! ### (a) No unauthorized decrease -/

theorem transfer_auth : NoUnauthorizedDecreaseFn spec Inv claim Auth .transfer := by
  intro ⟨dst, amount⟩ ctx w a _hInv hdec
  rw [Auth_transfer]
  by_cases hs : ctx.sender = a
  · exact hs
  · by_cases hsub : amount ≤ w.self.balances ctx.sender
    · by_cases hadd : (debit w.self.balances ctx.sender amount dst + amount).raw < wordBound
      · have hrun := transfer_ok ctx w dst amount hsub hadd
        simp [worldAfter, hrun] at hdec
        simp [claim, transferPost] at hdec
        by_cases ht : a = dst
        · subst ht
          simp [credit, debit, Function.update_of_ne (Ne.symm hs)] at hdec
          exact (Nat.not_lt.mpr (Nat.le_add_right _ _) hdec).elim
        · simp [credit_other _ ht, debit_other _ (Ne.symm hs)] at hdec
      · have hrun := transfer_reverts_on_overflow ctx w dst amount hsub (Nat.not_lt.mp hadd)
        simp [worldAfter, hrun] at hdec
    · have hrun := transfer_reverts_on_insufficient_balance ctx w dst amount (Nat.not_le.mp hsub)
      simp [worldAfter, hrun] at hdec

theorem transferFrom_auth : NoUnauthorizedDecreaseFn spec Inv claim Auth .transferFrom := by
  intro ⟨src, dst, amount⟩ ctx w a _hInv hdec
  rw [Auth_transferFrom]
  by_cases ha : src = a
  · by_cases hallow : amount ≤ w.self.allowances src ctx.sender
    · exact ⟨ha, hallow⟩
    · have hrun := transferFrom_reverts_on_insufficient_allowance ctx w src dst amount
        (Nat.not_le.mp hallow)
      simp [worldAfter, hrun] at hdec
  · by_cases hallow : amount ≤ w.self.allowances src ctx.sender
    · by_cases hsub : amount ≤ w.self.balances src
      · by_cases hadd : (debit w.self.balances src amount dst + amount).raw < wordBound
        · have hrun := transferFrom_ok ctx w src dst amount hallow hsub hadd
          simp [worldAfter, hrun] at hdec
          simp [claim, transferFromPost] at hdec
          by_cases ht : a = dst
          · subst ht
            simp [credit, debit, Function.update_of_ne (Ne.symm ha)] at hdec
            exact (Nat.not_lt.mpr (Nat.le_add_right _ _) hdec).elim
          · simp [credit_other _ ht, debit_other _ (Ne.symm ha)] at hdec
        · have hrun := transferFrom_reverts_on_overflow ctx w src dst amount hallow hsub
            (Nat.not_lt.mp hadd)
          simp [worldAfter, hrun] at hdec
      · have hrun := transferFrom_reverts_on_insufficient_balance ctx w src dst amount hallow
          (Nat.not_le.mp hsub)
        simp [worldAfter, hrun] at hdec
    · have hrun := transferFrom_reverts_on_insufficient_allowance ctx w src dst amount
        (Nat.not_le.mp hallow)
      simp [worldAfter, hrun] at hdec

theorem burn_auth : NoUnauthorizedDecreaseFn spec Inv claim Auth .burn := by
  intro amount ctx w a _hInv hdec
  rw [Auth_burn]
  by_cases hs : ctx.sender = a
  · exact hs
  · by_cases hsub : amount ≤ w.self.balances ctx.sender
    · by_cases hsupply : amount ≤ w.self.totalSupply
      · have hrun := burn_ok ctx w amount hsub hsupply
        simp [worldAfter, hrun] at hdec
        simp [claim, burnPost, debit_other _ (Ne.symm hs)] at hdec
      · have hrun := burn_reverts_on_insufficient_supply ctx w amount hsub
          (Nat.not_le.mp hsupply)
        simp [worldAfter, hrun] at hdec
    · have hrun := burn_reverts_on_insufficient_balance ctx w amount (Nat.not_le.mp hsub)
      simp [worldAfter, hrun] at hdec

theorem mint_auth : NoUnauthorizedDecreaseFn spec Inv claim Auth .mint := by
  intro ⟨dst, amount⟩ ctx w a _hInv hdec
  by_cases howner : ctx.sender = w.self.owner
  · by_cases hsupply : (w.self.totalSupply + amount).raw < wordBound
    · by_cases hadd : (w.self.balances dst + amount).raw < wordBound
      · have hrun := mint_ok ctx w dst amount howner hsupply hadd
        simp [worldAfter, hrun] at hdec
        simp [claim, mintPost] at hdec
        by_cases ht : a = dst
        · subst ht
          simp [credit] at hdec
          exact (Nat.not_lt.mpr (Nat.le_add_right _ _) hdec).elim
        · simp [credit_other _ ht] at hdec
      · have hrun := mint_reverts_on_balance_overflow ctx w dst amount howner hsupply
          (Nat.not_lt.mp hadd)
        simp [worldAfter, hrun] at hdec
    · have hrun := mint_reverts_on_overflow ctx w dst amount howner (Nat.not_lt.mp hsupply)
      simp [worldAfter, hrun] at hdec
  · have hrun := mint_reverts_for_non_owner ctx w dst amount howner
    simp [worldAfter, hrun] at hdec

theorem approve_auth : NoUnauthorizedDecreaseFn spec Inv claim Auth .approve := by
  intro ⟨spender, amount⟩ ctx w a _hInv hdec
  have ⟨w', hrun, hb⟩ := approve_preserves_balances ctx w spender amount
  simp [worldAfter, hrun] at hdec
  simp [claim, hb] at hdec

theorem balanceOf_auth : NoUnauthorizedDecreaseFn spec Inv claim Auth .balanceOf := by
  intro who ctx w a _hInv hdec
  unfold worldAfter at hdec
  rw [balanceOf_returns_stored_balance ctx w who] at hdec
  exact (Nat.lt_irrefl _ hdec).elim

theorem allowance_auth : NoUnauthorizedDecreaseFn spec Inv claim Auth .allowance := by
  intro ⟨owner, spender⟩ ctx w a _hInv hdec
  unfold worldAfter at hdec
  rw [allowance_returns_stored ctx w owner spender] at hdec
  exact (Nat.lt_irrefl _ hdec).elim

theorem totalSupply_auth : NoUnauthorizedDecreaseFn spec Inv claim Auth .totalSupply := by
  intro u ctx w a _hInv hdec
  unfold worldAfter at hdec
  rw [totalSupply_returns_stored ctx w] at hdec
  exact (Nat.lt_irrefl _ hdec).elim

theorem token_no_unauth {self : Address} :
    NoUnauthorizedDecrease spec self Inv claim Auth :=
  NoUnauthorizedDecrease.of_fns (C := spec) fun fn =>
    match fn with
    | .transfer => transfer_auth
    | .transferFrom => transferFrom_auth
    | .burn => burn_auth
    | .mint => mint_auth
    | .approve => approve_auth
    | .balanceOf => balanceOf_auth
    | .allowance => allowance_auth
    | .totalSupply => totalSupply_auth

/-! ### (b) Conservation -/

theorem transfer_conservesFn : ConservesFn spec Inv claim inflow .transfer := by
  intro ⟨dst, amount⟩ ctx w _hInv
  refine ⟨({ctx.sender, dst} : Finset Address), ?frame, ?sum⟩
  · intro a ha
    have hst : a ≠ ctx.sender ∧ a ≠ dst := by
      simpa [Finset.mem_insert, Finset.mem_singleton] using ha
    by_cases hsub : amount ≤ w.self.balances ctx.sender
    · by_cases hadd : (debit w.self.balances ctx.sender amount dst + amount).raw < wordBound
      · have ⟨w', hrun, hb⟩ :=
          transfer_preserves_other_balances ctx w dst amount a hst.1 hst.2 hsub hadd
        simp [worldAfter, hrun]; simp [claim, hb]
      · have hrun := transfer_reverts_on_overflow ctx w dst amount hsub (Nat.not_lt.mp hadd)
        simp [worldAfter, hrun]
    · have hrun := transfer_reverts_on_insufficient_balance ctx w dst amount (Nat.not_le.mp hsub)
      simp [worldAfter, hrun]
  · by_cases hsub : amount ≤ w.self.balances ctx.sender
    · by_cases hadd : (debit w.self.balances ctx.sender amount dst + amount).raw < wordBound
      · by_cases hne : ctx.sender = dst
        · subst hne
          have hbound : (w.self.balances ctx.sender).raw < wordBound := by
            have hle : amount.raw ≤ (w.self.balances ctx.sender).raw := hsub
            simp [debit, Function.update_self, Amount.raw_add, Amount.raw_sub] at hadd
            rw [Nat.sub_add_cancel hle] at hadd
            exact hadd
          have ⟨w', hrun, hb⟩ := transfer_self_transfer_is_noop ctx w amount hsub hbound
          simp [worldAfter, hrun]; simp [claim, hb, inflow, Call.ofCtx]
        · have hne' : ctx.sender ≠ dst := hne
          have hadd' : (w.self.balances dst + amount).raw < wordBound := by
            simpa [debit_other _ hne'.symm] using hadd
          have hrun := transfer_ok ctx w dst amount hsub
            (by simpa [debit_other _ hne'.symm] using hadd')
          have hcons := Proof.transfer_conserves ctx w dst amount hrun
          simp [worldAfter, hrun]
          rw [Finset.sum_pair hne', Finset.sum_pair hne']
          simp [claim, inflow, Call.ofCtx]
          exact le_of_eq (by simpa [Amount.raw_add] using congrArg Amount.raw hcons)
      · have hrun := transfer_reverts_on_overflow ctx w dst amount hsub (Nat.not_lt.mp hadd)
        simp [worldAfter, hrun]
    · have hrun := transfer_reverts_on_insufficient_balance ctx w dst amount (Nat.not_le.mp hsub)
      simp [worldAfter, hrun]

theorem transferFrom_conservesFn : ConservesFn spec Inv claim inflow .transferFrom := by
  intro ⟨src, dst, amount⟩ ctx w _hInv
  refine ⟨({src, dst} : Finset Address), ?frame, ?sum⟩
  · intro a ha
    have hst : a ≠ src ∧ a ≠ dst := by
      simpa [Finset.mem_insert, Finset.mem_singleton] using ha
    by_cases hallow : amount ≤ w.self.allowances src ctx.sender
    · by_cases hsub : amount ≤ w.self.balances src
      · by_cases hadd : (debit w.self.balances src amount dst + amount).raw < wordBound
        · have ⟨w', hrun, hb⟩ :=
            transferFrom_preserves_other_balances ctx w src dst amount a hst.1 hst.2
              hallow hsub hadd
          simp [worldAfter, hrun]; simp [claim, hb]
        · have hrun := transferFrom_reverts_on_overflow ctx w src dst amount hallow hsub
            (Nat.not_lt.mp hadd)
          simp [worldAfter, hrun]
      · have hrun := transferFrom_reverts_on_insufficient_balance ctx w src dst amount hallow
          (Nat.not_le.mp hsub)
        simp [worldAfter, hrun]
    · have hrun := transferFrom_reverts_on_insufficient_allowance ctx w src dst amount
        (Nat.not_le.mp hallow)
      simp [worldAfter, hrun]
  · by_cases hallow : amount ≤ w.self.allowances src ctx.sender
    · by_cases hsub : amount ≤ w.self.balances src
      · by_cases hadd : (debit w.self.balances src amount dst + amount).raw < wordBound
        · by_cases hne : src = dst
          · subst hne
            have hbound : (w.self.balances src).raw < wordBound := by
              have hle : amount.raw ≤ (w.self.balances src).raw := hsub
              simp [debit, Function.update_self, Amount.raw_add, Amount.raw_sub] at hadd
              rw [Nat.sub_add_cancel hle] at hadd
              exact hadd
            have ⟨w', hrun, hb⟩ :=
              transferFrom_self_transfer_is_noop ctx w src amount hallow hsub hbound
            simp [worldAfter, hrun]; simp [claim, hb, inflow, Call.ofCtx]
          · have hne' : src ≠ dst := hne
            have hadd' : (w.self.balances dst + amount).raw < wordBound := by
              simpa [debit_other _ hne'.symm] using hadd
            have ⟨w', hrun, hcons⟩ :=
              transferFrom_conserves_of_pre ctx w src dst amount hne' hallow hsub hadd'
            simp [worldAfter, hrun]
            rw [Finset.sum_pair hne', Finset.sum_pair hne']
            simp [claim, inflow, Call.ofCtx]
            exact le_of_eq (by simpa [Amount.raw_add] using congrArg Amount.raw hcons)
        · have hrun := transferFrom_reverts_on_overflow ctx w src dst amount hallow hsub
            (Nat.not_lt.mp hadd)
          simp [worldAfter, hrun]
      · have hrun := transferFrom_reverts_on_insufficient_balance ctx w src dst amount hallow
          (Nat.not_le.mp hsub)
        simp [worldAfter, hrun]
    · have hrun := transferFrom_reverts_on_insufficient_allowance ctx w src dst amount
        (Nat.not_le.mp hallow)
      simp [worldAfter, hrun]

theorem mint_conservesFn : ConservesFn spec Inv claim inflow .mint := by
  intro ⟨dst, amount⟩ ctx w _hInv
  refine ⟨({dst} : Finset Address), ?frame, ?sum⟩
  · intro a ha
    have hat : a ≠ dst := by simpa [Finset.mem_singleton] using ha
    by_cases howner : ctx.sender = w.self.owner
    · by_cases hsupply : (w.self.totalSupply + amount).raw < wordBound
      · by_cases hadd : (w.self.balances dst + amount).raw < wordBound
        · have ⟨w', hrun, hb⟩ :=
            mint_preserves_other_balances ctx w dst amount a hat howner hsupply hadd
          simp [worldAfter, hrun]; simp [claim, hb]
        · have hrun := mint_reverts_on_balance_overflow ctx w dst amount howner hsupply
            (Nat.not_lt.mp hadd)
          simp [worldAfter, hrun]
      · have hrun := mint_reverts_on_overflow ctx w dst amount howner (Nat.not_lt.mp hsupply)
        simp [worldAfter, hrun]
    · have hrun := mint_reverts_for_non_owner ctx w dst amount howner
      simp [worldAfter, hrun]
  · by_cases howner : ctx.sender = w.self.owner
    · by_cases hsupply : (w.self.totalSupply + amount).raw < wordBound
      · by_cases hadd : (w.self.balances dst + amount).raw < wordBound
        · have hrun := mint_ok ctx w dst amount howner hsupply hadd
          simp [Amount.raw_add] at hsupply hadd
          simp [worldAfter, hrun, claim, mintPost, credit, inflow,
            Call.ofCtx, Call.toCtx, howner, hsupply, hadd]
        · have hrun := mint_reverts_on_balance_overflow ctx w dst amount howner hsupply
            (Nat.not_lt.mp hadd)
          simp [worldAfter, hrun]
      · have hrun := mint_reverts_on_overflow ctx w dst amount howner (Nat.not_lt.mp hsupply)
        simp [worldAfter, hrun]
    · have hrun := mint_reverts_for_non_owner ctx w dst amount howner
      simp [worldAfter, hrun]

theorem burn_conservesFn : ConservesFn spec Inv claim inflow .burn := by
  intro amount ctx w _hInv
  refine ⟨({ctx.sender} : Finset Address), ?frame, ?sum⟩
  · intro a ha
    have hs : a ≠ ctx.sender := by simpa [Finset.mem_singleton] using ha
    by_cases hsub : amount ≤ w.self.balances ctx.sender
    · by_cases hsupply : amount ≤ w.self.totalSupply
      · have ⟨w', hrun, hb⟩ :=
          burn_preserves_other_balances ctx w amount a hs hsub hsupply
        simp [worldAfter, hrun]; simp [claim, hb]
      · have hrun := burn_reverts_on_insufficient_supply ctx w amount hsub
          (Nat.not_le.mp hsupply)
        simp [worldAfter, hrun]
    · have hrun := burn_reverts_on_insufficient_balance ctx w amount (Nat.not_le.mp hsub)
      simp [worldAfter, hrun]
  · by_cases hsub : amount ≤ w.self.balances ctx.sender
    · by_cases hsupply : amount ≤ w.self.totalSupply
      · have hrun := burn_ok ctx w amount hsub hsupply
        simp [worldAfter, hrun]
        simp [claim, burnPost, debit, inflow, Call.ofCtx]
      · have hrun := burn_reverts_on_insufficient_supply ctx w amount hsub
          (Nat.not_le.mp hsupply)
        simp [worldAfter, hrun]
    · have hrun := burn_reverts_on_insufficient_balance ctx w amount (Nat.not_le.mp hsub)
      simp [worldAfter, hrun]

theorem approve_conservesFn : ConservesFn spec Inv claim inflow .approve := by
  intro ⟨spender, amount⟩ ctx w _hInv
  refine ⟨∅, ?_, ?_⟩
  · intro a _
    have ⟨w', hrun, hb⟩ := approve_preserves_balances ctx w spender amount
    simp [worldAfter, hrun]; simp [claim, hb]
  · have ⟨_, hrun, _⟩ := approve_preserves_balances ctx w spender amount
    simp [worldAfter, hrun]

theorem balanceOf_conservesFn : ConservesFn spec Inv claim inflow .balanceOf := by
  intro who ctx w _hInv
  refine ⟨∅, ?_, ?_⟩
  · intro a _
    unfold worldAfter
    rw [balanceOf_returns_stored_balance ctx w who]
  · unfold worldAfter
    rw [balanceOf_returns_stored_balance ctx w who]
    simp [claim, inflow, Call.ofCtx]

theorem allowance_conservesFn : ConservesFn spec Inv claim inflow .allowance := by
  intro ⟨owner, spender⟩ ctx w _hInv
  refine ⟨∅, ?_, ?_⟩
  · intro a _
    unfold worldAfter
    rw [allowance_returns_stored ctx w owner spender]
  · unfold worldAfter
    rw [allowance_returns_stored ctx w owner spender]
    simp [claim, inflow, Call.ofCtx]

theorem totalSupply_conservesFn : ConservesFn spec Inv claim inflow .totalSupply := by
  intro u ctx w _hInv
  refine ⟨∅, ?_, ?_⟩
  · intro a _
    unfold worldAfter
    rw [totalSupply_returns_stored ctx w]
  · unfold worldAfter
    rw [totalSupply_returns_stored ctx w]
    simp [claim, inflow, Call.ofCtx]

theorem token_conservation {self : Address} :
    Conservation spec self Inv claim inflow :=
  Conservation.of_fns (C := spec) fun fn =>
    match fn with
    | .transfer => transfer_conservesFn
    | .transferFrom => transferFrom_conservesFn
    | .burn => burn_conservesFn
    | .mint => mint_conservesFn
    | .approve => approve_conservesFn
    | .balanceOf => balanceOf_conservesFn
    | .allowance => allowance_conservesFn
    | .totalSupply => totalSupply_conservesFn

/-! ### (c) Invariant preservation -/

theorem transfer_preserves_inv : PreservesInvFn spec Inv .transfer := by
  intro ⟨dst, amount⟩ ctx w hInv
  by_cases hsub : amount ≤ w.self.balances ctx.sender
  · by_cases hadd : (debit w.self.balances ctx.sender amount dst + amount).raw < wordBound
    · have hrun := transfer_ok ctx w dst amount hsub hadd
      simp [worldAfter, hrun]
      exact inv_of_transferPost w.self ctx.sender dst amount hInv hsub
    · have hrun := transfer_reverts_on_overflow ctx w dst amount hsub (Nat.not_lt.mp hadd)
      simp [worldAfter, hrun]
      exact hInv
  · have hrun := transfer_reverts_on_insufficient_balance ctx w dst amount (Nat.not_le.mp hsub)
    simp [worldAfter, hrun]
    exact hInv

theorem transferFrom_preserves_inv : PreservesInvFn spec Inv .transferFrom := by
  intro ⟨src, dst, amount⟩ ctx w hInv
  by_cases hallow : amount ≤ w.self.allowances src ctx.sender
  · by_cases hsub : amount ≤ w.self.balances src
    · by_cases hadd : (debit w.self.balances src amount dst + amount).raw < wordBound
      · have hrun := transferFrom_ok ctx w src dst amount hallow hsub hadd
        simp [worldAfter, hrun]
        exact inv_of_transferPost w.self src dst amount hInv hsub
      · have hrun := transferFrom_reverts_on_overflow ctx w src dst amount hallow hsub
          (Nat.not_lt.mp hadd)
        simp [worldAfter, hrun]
        exact hInv
    · have hrun := transferFrom_reverts_on_insufficient_balance ctx w src dst amount hallow
        (Nat.not_le.mp hsub)
      simp [worldAfter, hrun]
      exact hInv
  · have hrun := transferFrom_reverts_on_insufficient_allowance ctx w src dst amount
      (Nat.not_le.mp hallow)
    simp [worldAfter, hrun]
    exact hInv

theorem mint_preserves_inv : PreservesInvFn spec Inv .mint := by
  intro ⟨dst, amount⟩ ctx w hInv
  by_cases howner : ctx.sender = w.self.owner
  · by_cases hsupply : (w.self.totalSupply + amount).raw < wordBound
    · by_cases hadd : (w.self.balances dst + amount).raw < wordBound
      · have hrun := mint_ok ctx w dst amount howner hsupply hadd
        simp [worldAfter, hrun]
        exact inv_of_mintPost w.self dst amount hInv
      · have hrun := mint_reverts_on_balance_overflow ctx w dst amount howner hsupply
          (Nat.not_lt.mp hadd)
        simp [worldAfter, hrun]
        exact hInv
    · have hrun := mint_reverts_on_overflow ctx w dst amount howner (Nat.not_lt.mp hsupply)
      simp [worldAfter, hrun]
      exact hInv
  · have hrun := mint_reverts_for_non_owner ctx w dst amount howner
    simp [worldAfter, hrun]
    exact hInv

theorem burn_preserves_inv : PreservesInvFn spec Inv .burn := by
  intro amount ctx w hInv
  by_cases hsub : amount ≤ w.self.balances ctx.sender
  · by_cases hsupply : amount ≤ w.self.totalSupply
    · have hrun := burn_ok ctx w amount hsub hsupply
      simp [worldAfter, hrun]
      exact inv_of_burnPost w.self ctx.sender amount hInv hsub
    · have hrun := burn_reverts_on_insufficient_supply ctx w amount hsub (Nat.not_le.mp hsupply)
      simp [worldAfter, hrun]
      exact hInv
  · have hrun := burn_reverts_on_insufficient_balance ctx w amount (Nat.not_le.mp hsub)
    simp [worldAfter, hrun]
    exact hInv

theorem approve_preserves_inv : PreservesInvFn spec Inv .approve := by
  intro ⟨spender, amount⟩ ctx w hInv
  have hrun := approve_ok ctx w spender amount
  simp [worldAfter, hrun]
  obtain ⟨H, h0, hsum⟩ := hInv
  exact ⟨H, fun a ha => h0 a ha, hsum⟩

theorem balanceOf_preserves_inv : PreservesInvFn spec Inv .balanceOf := by
  intro who ctx w hInv
  unfold worldAfter
  rw [balanceOf_returns_stored_balance ctx w who]
  exact hInv

theorem allowance_preserves_inv : PreservesInvFn spec Inv .allowance := by
  intro ⟨owner, spender⟩ ctx w hInv
  unfold worldAfter
  rw [allowance_returns_stored ctx w owner spender]
  exact hInv

theorem totalSupply_preserves_inv : PreservesInvFn spec Inv .totalSupply := by
  intro u ctx w hInv
  unfold worldAfter
  rw [totalSupply_returns_stored ctx w]
  exact hInv

theorem token_preserves_inv {self : Address} : PreservesInv spec self Inv :=
  PreservesInv.of_fns (C := spec) fun fn =>
    match fn with
    | .transfer => transfer_preserves_inv
    | .transferFrom => transferFrom_preserves_inv
    | .burn => burn_preserves_inv
    | .mint => mint_preserves_inv
    | .approve => approve_preserves_inv
    | .balanceOf => balanceOf_preserves_inv
    | .allowance => allowance_preserves_inv
    | .totalSupply => totalSupply_preserves_inv

/-- Environment steps are a no-op on storage-only `Inv`. -/
theorem token_inv_rely {self : Address} :
    PreservesInvEnv spec Inv (HasRely.rely (C := spec) self) := by
  intro w x' hw _
  exact hw

/-- Default deployment (empty storage) establishes `Inv`. -/
theorem token_deployed_inv (w : World)
    (h : Deployed spec w) : Inv w := by
  change w.self = default at h
  refine ⟨∅, ?_, ?_⟩
  · intro a _
    rw [h]; rfl
  · rw [h]; rfl

/-- Deployment from empty balances establishes `Inv`. -/
theorem «constructor_inv» (owner : Address) (supply : Amount tokenAsset) (ctx : Ctx)
    (w : World)
    (hempty : ∀ a, w.self.balances a = 0)
    (htot : w.self.totalSupply = 0)
    (hfit : supply.raw < wordBound) :
    Inv (worldAfter (Token.constructor owner supply) ctx w) := by
  have hsupply : (w.self.totalSupply + supply).raw < wordBound := by
    simpa [htot, Amount.raw_add, Amount.raw_zero] using hfit
  have hadd : (w.self.balances owner + supply).raw < wordBound := by
    simpa [hempty, Amount.raw_add, Amount.raw_zero] using hfit
  have hrun := ctor_ok ctx w owner supply hsupply hadd
  simp [worldAfter, hrun, Inv, InvStorage]
  refine ⟨{owner}, ?_, ?_⟩
  · intro a ha
    have hne : a ≠ owner := by simpa [Finset.mem_singleton] using ha
    simp [ctorPost, credit, Function.update_of_ne hne, hempty]
  · simp [ctorPost, credit, Finset.sum_singleton, Function.update_self, hempty, htot]

namespace Proof

private theorem le_add (x y : Amount tokenAsset) : x ≤ x + y := by
  simp [Amount.le_iff, Amount.raw_add]

private theorem raw_ite (p : Prop) [Decidable p] {α : Asset} (x y : Amount α) :
    (if p then x else y).raw = if p then x.raw else y.raw := by
  split_ifs <;> rfl

private theorem nat_ite_cover (f : Nat → Nat) (src dst a n : Nat)
    (hn : n ≤ f src) :
    f a ≤
      (if a = dst then (if dst = src then f src - n else f dst) + n
        else if a = src then f src - n else f a) +
      (if src = a then n else 0) := by
  split_ifs <;> subst_vars <;> omega

private theorem balances_transferPost (σ : Storage) (src dst : Address)
    (n : Amount tokenAsset) (a : Address) (hn : n ≤ σ.balances src) :
    σ.balances a ≤ (transferPost σ src dst n).balances a +
      if src = a then n else 0 := by
  simp [Amount.le_iff, Amount.raw_add, transferPost, credit, debit,
    Amount.raw_sub, Function.update_apply, raw_ite] at hn ⊢
  exact nat_ite_cover (fun i => (σ.balances i).raw) src dst a n.raw hn

private theorem nat_ite_burn (f : Nat → Nat) (src a n : Nat)
    (hn : n ≤ f src) :
    f a ≤ (if a = src then f src - n else f a) + (if src = a then n else 0) := by
  split_ifs <;> subst_vars <;> omega

private theorem balances_burnPost (σ : Storage) (src : Address)
    (n : Amount tokenAsset) (a : Address) (hn : n ≤ σ.balances src) :
    σ.balances a ≤ (burnPost σ src n).balances a +
      if src = a then n else 0 := by
  simp [Amount.le_iff, Amount.raw_add, burnPost, debit, Amount.raw_sub,
    Function.update_apply, raw_ite] at hn ⊢
  exact nat_ite_burn (fun i => (σ.balances i).raw) src a n.raw hn

private theorem spent_covers_ok (self : Address) (c : Call spec)
    (w w' : World) (a : Address) {r : spec.Ret c.fn}
    (h : spec.exec c.fn c.args (c.toCtx self) w = .ok (r, w')) :
    w.self.balances a ≤ w'.self.balances a + spentCall a c := by
  revert r h
  rcases c with ⟨sender, value, ts, bn, fn, args⟩
  cases fn <;> intro r h
  case transfer =>
    rcases args with ⟨dst, amount⟩
    have hrun : Tx.run (transfer dst amount)
        { sender, value, timestamp := ts, blockNumber := bn, self } w =
          .ok (r, w') := by
      simpa [Tx.run, spec_exec_transfer, Call.toCtx] using h
    have hr := transfer_returns_true { sender, value, timestamp := ts, blockNumber := bn, self } w dst amount
      hrun
    subst hr
    have ⟨hsub, _, hw'⟩ :=
      transfer_ok_inv { sender, value, timestamp := ts, blockNumber := bn, self } w dst amount hrun
    simp [spentCall, hw', Call.toCtx]
    exact balances_transferPost w.self sender dst amount a hsub
  case burn =>
    have hrun : Tx.run (burn args) { sender, value, timestamp := ts, blockNumber := bn, self } w =
        .ok (r, w') := by
      simpa [Tx.run, spec_exec_burn, Call.toCtx] using h
    by_cases hsub : args ≤ w.self.balances sender
    · by_cases hsupply : args ≤ w.self.totalSupply
      · have hok := burn_ok { sender, value, timestamp := ts, blockNumber := bn, self } w args hsub hsupply
        rw [hok] at hrun
        obtain ⟨rfl, rfl⟩ := hrun
        simp [spentCall]
        exact balances_burnPost w.self sender args a hsub
      · have herr := burn_reverts_on_insufficient_supply
          { sender, value, timestamp := ts, blockNumber := bn, self } w args hsub (Nat.not_le.mp hsupply)
        rw [herr] at hrun; cases hrun
    · have herr := burn_reverts_on_insufficient_balance
        { sender, value, timestamp := ts, blockNumber := bn, self } w args (Nat.not_le.mp hsub)
      rw [herr] at hrun; cases hrun
  case transferFrom =>
    rcases args with ⟨src, dst, amount⟩
    have hrun : Tx.run (transferFrom src dst amount)
        { sender, value, timestamp := ts, blockNumber := bn, self } w = .ok (r, w') := by
      simpa [Tx.run, spec_exec_transferFrom, Call.toCtx] using h
    have hr := transferFrom_returns_true { sender, value, timestamp := ts, blockNumber := bn, self } w
      src dst amount hrun
    subst hr
    have ⟨_, hsub, _, hw'⟩ :=
      transferFrom_ok_inv { sender, value, timestamp := ts, blockNumber := bn, self } w src dst amount hrun
    simp [spentCall, hw', Call.toCtx]
    exact balances_transferPost w.self src dst amount a hsub
  case mint =>
    rcases args with ⟨dst, amount⟩
    have hrun : Tx.run (mint dst amount)
        { sender, value, timestamp := ts, blockNumber := bn, self } w = .ok (r, w') := by
      simpa [Tx.run, spec_exec_mint, Call.toCtx] using h
    simp [spentCall]
    by_cases ho : sender = w.self.owner
    · by_cases hts : (w.self.totalSupply + amount).raw < wordBound
      · by_cases hb : (w.self.balances dst + amount).raw < wordBound
        · have hok := mint_ok { sender, value, timestamp := ts, blockNumber := bn, self } w dst amount
            ho hts hb
          rw [hok] at hrun
          obtain ⟨rfl, rfl⟩ := hrun
          simp [mintPost, credit, Amount.le_iff, Amount.raw_add]
          by_cases hd : dst = a
          · rw [hd, Function.update_self]
            exact Nat.le_add_right _ _
          · rw [Function.update_of_ne (Ne.symm hd)]
        · have herr := mint_reverts_on_balance_overflow
            { sender, value, timestamp := ts, blockNumber := bn, self } w dst amount ho hts
            (Nat.not_lt.mp hb)
          rw [herr] at hrun; cases hrun
      · have herr := mint_reverts_on_overflow
          { sender, value, timestamp := ts, blockNumber := bn, self } w dst amount ho (Nat.not_lt.mp hts)
        rw [herr] at hrun; cases hrun
    · have herr := mint_reverts_for_non_owner
        { sender, value, timestamp := ts, blockNumber := bn, self } w dst amount ho
      rw [herr] at hrun; cases hrun
  case approve =>
    rcases args with ⟨spender, amount⟩
    have hrun : Tx.run (approve spender amount)
        { sender, value, timestamp := ts, blockNumber := bn, self } w = .ok (r, w') := by
      simpa [Tx.run, spec_exec_approve, Call.toCtx] using h
    have ⟨_, hok, hb⟩ :=
      approve_preserves_balances { sender, value, timestamp := ts, blockNumber := bn, self } w spender amount
    simp [spentCall]
    rw [hok] at hrun
    obtain ⟨rfl, rfl⟩ := hrun
    simp [hb]
  case balanceOf =>
    have hrun : Tx.run (balanceOf args)
        { sender, value, timestamp := ts, blockNumber := bn, self } w = .ok (r, w') := by
      simpa [Tx.run, spec_exec_balanceOf, Call.toCtx] using h
    rw [balanceOf_returns_stored_balance { sender, value, timestamp := ts, blockNumber := bn, self } w args]
      at hrun
    obtain ⟨rfl, rfl⟩ := hrun
    simp [spentCall]
  case allowance =>
    rcases args with ⟨owner, spender⟩
    have hrun : Tx.run (allowance owner spender)
        { sender, value, timestamp := ts, blockNumber := bn, self } w = .ok (r, w') := by
      simpa [Tx.run, spec_exec_allowance, Call.toCtx] using h
    rw [allowance_returns_stored { sender, value, timestamp := ts, blockNumber := bn, self } w owner spender]
      at hrun
    obtain ⟨rfl, rfl⟩ := hrun
    simp [spentCall]
  case totalSupply =>
    have hrun : Tx.run totalSupply { sender, value, timestamp := ts, blockNumber := bn, self } w =
        .ok (r, w') := by
      simpa [Tx.run, spec_exec_totalSupply, Call.toCtx] using h
    rw [totalSupply_returns_stored { sender, value, timestamp := ts, blockNumber := bn, self } w] at hrun
    obtain ⟨rfl, rfl⟩ := hrun
    simp [spentCall]

private theorem spent_covers_accepted (self : Address) (c : Call spec)
    (w : World) (a : Address)
    (hacc : accepted self c w = true) :
    w.self.balances a ≤ (step self (.call c) w).self.balances a +
      spentCall a c := by
  obtain ⟨hvo, _, ⟨⟨r, w'⟩, hrun, hstep⟩⟩ := accepted_ok hacc
  have hv : c.value = 0 :=
    spec.value_eq_zero_of_valueOk (by cases c.fn <;> rfl) hvo
  rw [hv, World.creditValue_zero] at hrun
  rw [hstep]
  exact spent_covers_ok self c w w' a hrun

private theorem token_balances_sum (w : State) :
    ∃ H : Finset Address,
      (∀ a, a ∉ H → w.self.balances a = 0) ∧
      H.sum (fun a => (w.self.balances a).raw) = w.self.totalSupply.raw :=
  inv_of_reachable (C := spec) (rely := HasRely.rely (C := spec) w.addr)
    (self := w.addr) token_deployed_inv
    (PreservesInv.toAt token_preserves_inv) token_inv_rely w.reachable

theorem token_solvent (w : State) :
    ∀ A : Finset Address, ∑ a ∈ A, w.self.balances a ≤ w.self.totalSupply := by
  intro A
  obtain ⟨H, h0, hsum⟩ := token_balances_sum w
  have hfilter :
      ∑ a ∈ A, (w.self.balances a).raw =
        ∑ a ∈ A.filter (· ∈ H), (w.self.balances a).raw := by
    rw [Finset.sum_filter]
    refine Finset.sum_congr rfl ?_
    intro a _ha
    split_ifs with hH
    · rfl
    · simp [h0 a hH]
  have hsub : A.filter (· ∈ H) ⊆ H := fun a ha => (Finset.mem_filter.mp ha).2
  have hle :
      ∑ a ∈ A.filter (· ∈ H), (w.self.balances a).raw ≤
        ∑ a ∈ H, (w.self.balances a).raw := by
    rw [← Finset.sum_sdiff hsub]
    exact Nat.le_add_left _ _
  have : (∑ a ∈ A, w.self.balances a).raw ≤ w.self.totalSupply.raw := by
    rw [Amount.sum_raw, hfilter, ← hsum]
    exact hle
  simpa [Amount.le_iff] using this

private theorem foldAccepted_raw_add {s : State} (t : Txs s) (a : Address)
    (x : Amount tokenAsset) :
    (t.foldAccepted (fun acc c _ => acc + HasSpent.spentCall (C := spec) a c) x).raw =
      x.raw + (Txs.spent t a).raw := by
  induction t generalizing x with
  | nil => simp [Txs.foldAccepted, Txs.spent, Amount.raw_add]
  | @call s c hne rest ih =>
    simp [Txs.foldAccepted, Txs.spent]
    split_ifs
    · have hx := ih (x + HasSpent.spentCall (C := spec) a (c))
      have hsc := ih (HasSpent.spentCall (C := spec) a (c))
      rw [hx, hsc]
      exact Nat.add_assoc _ _ _
    · exact ih x
  | @env s _x' _hr rest ih =>
    simp [Txs.foldAccepted, Txs.spent]
    exact ih x

theorem token_no_unauthorized_extraction (w : State) (t : Txs w) (a : Address) :
    w.self.balances a ≤ t.end.self.balances a + t.spent a := by
  induction t with
  | nil =>
    simp [Txs.spent, Txs.foldAccepted, Amount.le_iff, Amount.raw_add]
  | @call s c hne rest ih =>
    simp [Txs.spent, Txs.foldAccepted]
    by_cases hacc : accepted s.addr c s.w = true
    · have hcov := spent_covers_accepted s.addr c s.w a hacc
      have hstepEq : (s.afterCall c hne).w = step s.addr (.call c) s.w :=
        State.afterCall_w s c hne
      have hthis : s.self.balances a ≤
          (s.afterCall c hne).self.balances a + spentCall a c := by
        simpa [State.self, hstepEq] using hcov
      simp [Amount.le_iff, Amount.raw_add] at hthis ih
      have hfold := foldAccepted_raw_add rest a
        (HasSpent.spentCall (C := spec) a c)
      simp [Amount.le_iff, Amount.raw_add, Txs.spent, Txs.foldAccepted, hacc,
        HasSpent.spentCall] at hthis ih hfold ⊢
      rw [hfold]
      refine Nat.le_trans hthis ?_
      have hih := Nat.add_le_add_right ih (spentCall a c).raw
      convert hih using 1
      ac_rfl
    · have hfalse : accepted s.addr c s.w = false :=
        Bool.eq_false_iff.mpr hacc
      have hstep := step_of_not_accepted hfalse
      have hs : (s.afterCall c hne).self = s.self := by
        simp only [State.self, State.afterCall_w]
        exact congrArg World.self hstep
      simp [hs, Txs.spent, Txs.foldAccepted, hfalse] at ih ⊢
      exact ih
  | @env s x' hr rest ih =>
    have hs : (s.afterEnv x' hr).self = s.self := State.afterEnv_self s x' hr
    simpa [Txs.spent, Txs.foldAccepted, hs] using ih

end Proof

end Token
