import Mathlib.Tactic.SplitIfs
import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Lsc.Security.Wealth
import Lsc.Security.WealthTheorems
import Lsc.Security.InvariantTheorems
import Examples.Token.Spec
import Examples.Token.Proofs.Tx

open Lsc Lsc.Security Token

namespace Token

/-!
`Token.Fn` / `Token.entry` / `Token.spec` are generated by `lsc_contract`
(constructor excluded). No pause. `claim` / `Auth` / `Inv` live in `Spec.lean`.
-/

theorem inv_solvent (self : Address) (w : World Storage Unit Event) (h : Inv w) :
    Solvent claim holdings self w := by
  obtain ⟨H, h0, hs⟩ := h
  refine ⟨H, ?_, hs.le⟩
  intro a ha
  have hraw := congrArg Amount.raw (h0 a ha)
  simp [claim]
  exact hraw.trans (Amount.raw_ofNat 0)

/-! ### Auth reductions -/

lemma Auth_transfer (a : Address) (ctx : Ctx) (dst : Address)
    (n : Amount tokenAsset) (s : Storage) :
    Auth a (Call.ofCtx ctx .transfer (dst, n)) s ↔ ctx.sender = a :=
  Iff.rfl

lemma Auth_burn (a : Address) (ctx : Ctx) (n : Amount tokenAsset) (s : Storage) :
    Auth a (Call.ofCtx ctx .burn n) s ↔ ctx.sender = a :=
  Iff.rfl

lemma Auth_transferFrom (a : Address) (ctx : Ctx) (src dst : Address)
    (n : Amount tokenAsset) (s : Storage) :
    Auth a (Call.ofCtx ctx .transferFrom (src, dst, n)) s ↔
      src = a ∧ n ≤ s.allowances src ctx.sender :=
  Iff.rfl

/-! ### Sum helpers for `Inv` -/

private abbrev rawBals (bals : Address → Amount tokenAsset) : Address → Nat :=
  fun a => (bals a).raw

private theorem rawBals_update (bals : Address → Amount tokenAsset) (src : Address)
    (n : Amount tokenAsset) :
    rawBals (Function.update bals src n) =
      Function.update (rawBals bals) src n.raw := by
  funext a
  by_cases h : a = src <;> simp [rawBals, Function.update, h]

private theorem nat_sum_update_sub (H : Finset Address) (f : Address → Nat)
    {i : Address} (hi : i ∈ H) {n : Nat} (hn : n ≤ f i) :
    H.sum (Function.update f i (f i - n)) + n = H.sum f := by
  have hS := sum_update_mem H f hi (f i - n)
  have : f i - n + n = f i := Nat.sub_add_cancel hn
  omega

private theorem nat_sum_update_add (H : Finset Address) (f : Address → Nat)
    {i : Address} (hi : i ∈ H) (n : Nat) :
    H.sum (Function.update f i (f i + n)) = H.sum f + n := by
  have hS := sum_update_mem H f hi (f i + n)
  omega

private theorem sum_debit (H : Finset Address) (bals : Address → Amount tokenAsset)
    {src : Address} (hs : src ∈ H) {n : Amount tokenAsset}
    (hn : n.raw ≤ (bals src).raw) :
    H.sum (rawBals (debit bals src n)) + n.raw = H.sum (rawBals bals) := by
  unfold debit
  rw [rawBals_update, Amount.raw_sub]
  exact nat_sum_update_sub H (rawBals bals) hs hn

private theorem inv_of_transferPost (σ : Storage) (src dst : Address)
    (n : Amount tokenAsset)
    (hInv : InvStorage σ) (hn : n ≤ σ.balances src) :
    InvStorage (transferPost σ src dst n) := by
  obtain ⟨H, h0, hsum⟩ := hInv
  have hn' : n.raw ≤ (σ.balances src).raw := hn
  by_cases hsrc : src ∈ H
  · by_cases hto : dst ∈ H
    · refine ⟨H, ?_, ?_⟩
      · intro a ha
        have ha_to : a ≠ dst := by intro h; subst h; exact ha hto
        have ha_src : a ≠ src := by intro h; subst h; exact ha hsrc
        simp [transferPost, credit_other _ ha_to, debit_other _ ha_src]
        exact h0 a ha
      · have hs1 := sum_debit H σ.balances hsrc hn'
        let f := rawBals (debit σ.balances src n)
        have hsum' :
            H.sum (rawBals (Function.update (debit σ.balances src n) dst
              (debit σ.balances src n dst + n))) =
              H.sum f + n.raw := by
          rw [rawBals_update, Amount.raw_add]
          exact nat_sum_update_add H f hto n.raw
        change H.sum (rawBals (transferPost σ src dst n).balances) =
          (transferPost σ src dst n).totalSupply.raw
        simp only [transferPost, credit]
        exact (hsum'.trans hs1).trans hsum
    · have hne : src ≠ dst := by intro h; subst h; exact hto hsrc
      refine ⟨insert dst H, ?_, ?_⟩
      · intro a ha
        have hat : a ≠ dst := by
          intro h; subst h; exact ha (Finset.mem_insert_self _ _)
        have haH : a ∉ H := fun hH => ha (Finset.mem_insert_of_mem hH)
        have ha_src : a ≠ src := by intro h; subst h; exact haH hsrc
        simp [transferPost, credit_other _ hat, debit_other _ ha_src]
        exact h0 a haH
      · have hs1 := sum_debit H σ.balances hsrc hn'
        let f := rawBals (debit σ.balances src n)
        have hframe := sum_update_not_mem H f hto (f dst + n.raw)
        have hb0 : σ.balances dst = 0 := h0 dst hto
        have hdt : debit σ.balances src n dst = 0 := by
          simp [debit, Function.update_of_ne hne.symm, hb0]
        have hsum' :
            (∑ a ∈ insert dst H, rawBals (transferPost σ src dst n).balances a) =
              H.sum (rawBals σ.balances) := by
          rw [Finset.sum_insert hto]
          simp only [transferPost, credit]
          rw [rawBals_update, Amount.raw_add, Function.update_self, hframe]
          simp [hdt, Amount.raw_zero]
          rw [Nat.add_comm]
          exact hs1
        change (∑ a ∈ insert dst H,
            ((transferPost σ src dst n).balances a).raw) =
          (transferPost σ src dst n).totalSupply.raw
        simpa [transferPost] using hsum'.trans hsum
  · have hb0 : σ.balances src = 0 := h0 src hsrc
    have hn0 : n = 0 := by
      cases n with | mk nraw =>
      have hz : (σ.balances src).raw = 0 := by
        simpa [Amount.raw_zero] using congrArg Amount.raw hb0
      have : nraw = 0 := Nat.eq_zero_of_le_zero (hn'.trans_eq hz)
      subst this
      rfl
    subst hn0
    have hbals : (transferPost σ src dst 0).balances = σ.balances := by
      have hsub0 : σ.balances src - 0 = σ.balances src :=
        Amount.ext (by simp [Amount.raw_sub, Amount.raw_zero])
      have hadd0 (x : Amount tokenAsset) : x + 0 = x :=
        Amount.ext (by simp [Amount.raw_add, Amount.raw_zero])
      funext a
      simp [transferPost, credit, debit, hsub0, hadd0, Function.update_eq_self]
    refine ⟨H, fun a ha => ?_, ?_⟩
    · rw [show (transferPost σ src dst 0).balances a = σ.balances a from
        congrFun hbals a]
      exact h0 a ha
    · have hsum' :
          (∑ a ∈ H, ((transferPost σ src dst 0).balances a).raw) =
            H.sum (fun a => (σ.balances a).raw) := by
        apply Finset.sum_congr rfl
        intro a _; rw [hbals]
      simpa [transferPost] using hsum'.trans hsum

private theorem inv_of_mintPost (σ : Storage) (dst : Address) (n : Amount tokenAsset)
    (hInv : InvStorage σ) :
    InvStorage (mintPost σ dst n) := by
  obtain ⟨H, h0, hsum⟩ := hInv
  refine ⟨insert dst H, ?_, ?_⟩
  · intro a ha
    have hat : a ≠ dst := by
      intro h; subst h; exact ha (Finset.mem_insert_self _ _)
    have haH : a ∉ H := fun hH => ha (Finset.mem_insert_of_mem hH)
    simp [mintPost, credit_other _ hat]
    exact h0 a haH
  · by_cases ht : dst ∈ H
    · rw [Finset.insert_eq_of_mem ht]
      let f := rawBals σ.balances
      have hcancel :
          H.sum (rawBals (Function.update σ.balances dst (σ.balances dst + n))) =
            H.sum f + n.raw := by
        rw [rawBals_update, Amount.raw_add]
        exact nat_sum_update_add H f ht n.raw
      change H.sum (fun a => ((mintPost σ dst n).balances a).raw) =
        (mintPost σ dst n).totalSupply.raw
      simp only [mintPost, credit]
      simpa [rawBals] using hcancel.trans (by rw [hsum])
    · let f := rawBals σ.balances
      have hframe := sum_update_not_mem H f ht (f dst + n.raw)
      have hb0 : σ.balances dst = 0 := h0 dst ht
      have hsum' :
          (∑ a ∈ insert dst H, ((mintPost σ dst n).balances a).raw) =
            H.sum f + n.raw := by
        rw [Finset.sum_insert ht]
        simp only [mintPost, credit, Function.update_self]
        change (σ.balances dst + n).raw +
            H.sum (rawBals (Function.update σ.balances dst (σ.balances dst + n))) =
          H.sum f + n.raw
        rw [rawBals_update, Amount.raw_add, hb0, Amount.raw_zero, Nat.zero_add]
        have hf0 : f dst = 0 := by simpa [rawBals, Amount.raw_zero] using congrArg Amount.raw hb0
        have hfr : H.sum (Function.update f dst n.raw) = H.sum f := by
          simpa [hf0, Nat.zero_add] using hframe
        rw [hfr, Nat.add_comm]
      change (∑ a ∈ insert dst H, ((mintPost σ dst n).balances a).raw) =
        (mintPost σ dst n).totalSupply.raw
      simpa [mintPost] using hsum'.trans (by rw [hsum])

private theorem inv_of_burnPost (σ : Storage) (src : Address) (n : Amount tokenAsset)
    (hInv : InvStorage σ) (hn : n ≤ σ.balances src) :
    InvStorage (burnPost σ src n) := by
  obtain ⟨H, h0, hsum⟩ := hInv
  have hn' : n.raw ≤ (σ.balances src).raw := hn
  by_cases hs : src ∈ H
  · refine ⟨H, ?_, ?_⟩
    · intro a ha
      have ha_src : a ≠ src := by intro h; subst h; exact ha hs
      simp [burnPost, debit_other _ ha_src]
      exact h0 a ha
    · have hs1 := sum_debit H σ.balances hs hn'
      have hsumd :
          H.sum (rawBals (debit σ.balances src n)) =
            H.sum (rawBals σ.balances) - n.raw := by
        rw [← Nat.add_sub_cancel (H.sum (rawBals (debit σ.balances src n))) n.raw, hs1]
      change H.sum (fun a => ((burnPost σ src n).balances a).raw) =
        (burnPost σ src n).totalSupply.raw
      simp only [burnPost, debit, Amount.raw_sub]
      simpa [rawBals] using hsumd.trans (by rw [hsum])
  · have hb0 : σ.balances src = 0 := h0 src hs
    have hn0 : n = 0 := by
      cases n with | mk nraw =>
      have hz : (σ.balances src).raw = 0 := by
        simpa [Amount.raw_zero] using congrArg Amount.raw hb0
      have : nraw = 0 := Nat.eq_zero_of_le_zero (hn'.trans_eq hz)
      subst this
      rfl
    subst hn0
    have hbals0 : σ.balances src - 0 = σ.balances src := Amount.ext (by simp [Amount.raw_sub])
    refine ⟨H, ?_, ?_⟩
    · intro a ha
      simp [burnPost, debit, hbals0, Function.update_eq_self]
      exact h0 a ha
    · simpa [burnPost, debit, hbals0, Function.update_eq_self, Amount.raw_zero, Amount.raw_sub,
        Nat.sub_zero] using hsum

/-! ### (a) No unauthorized decrease -/

theorem transfer_auth : NoUnauthorizedDecreaseFn spec Inv claim Auth .transfer := by
  intro ⟨dst, amount⟩ ctx w a _hInv hdec
  rw [Auth_transfer]
  by_cases hs : ctx.sender = a
  · exact hs
  · by_cases hsub : amount ≤ w.self.balances ctx.sender
    · by_cases hadd : (debit w.self.balances ctx.sender amount dst + amount).raw < wordBound
      · have hrun := transfer_ok ctx w dst amount hsub hadd
        simp [worldAfter, hrun] at hdec
        simp [claim, transferPost] at hdec
        by_cases ht : a = dst
        · subst ht
          simp [credit, debit, Function.update_of_ne (Ne.symm hs)] at hdec
        · simp [credit_other _ ht, debit_other _ (Ne.symm hs)] at hdec
      · have hrun := transfer_reverts_on_overflow ctx w dst amount hsub (Nat.not_lt.mp hadd)
        simp [worldAfter, hrun] at hdec
    · have hrun := transfer_reverts_on_insufficient_balance ctx w dst amount (Nat.not_le.mp hsub)
      simp [worldAfter, hrun] at hdec

theorem transferFrom_auth : NoUnauthorizedDecreaseFn spec Inv claim Auth .transferFrom := by
  intro ⟨src, dst, amount⟩ ctx w a _hInv hdec
  rw [Auth_transferFrom]
  by_cases ha : src = a
  · by_cases hallow : amount ≤ w.self.allowances src ctx.sender
    · exact ⟨ha, hallow⟩
    · have hrun := transferFrom_reverts_on_insufficient_allowance ctx w src dst amount
        (Nat.not_le.mp hallow)
      simp [worldAfter, hrun] at hdec
  · by_cases hallow : amount ≤ w.self.allowances src ctx.sender
    · by_cases hsub : amount ≤ w.self.balances src
      · by_cases hadd : (debit w.self.balances src amount dst + amount).raw < wordBound
        · have hrun := transferFrom_ok ctx w src dst amount hallow hsub hadd
          simp [worldAfter, hrun] at hdec
          simp [claim, transferFromPost] at hdec
          by_cases ht : a = dst
          · subst ht
            simp [credit, debit, Function.update_of_ne (Ne.symm ha)] at hdec
          · simp [credit_other _ ht, debit_other _ (Ne.symm ha)] at hdec
        · have hrun := transferFrom_reverts_on_overflow ctx w src dst amount hallow hsub
            (Nat.not_lt.mp hadd)
          simp [worldAfter, hrun] at hdec
      · have hrun := transferFrom_reverts_on_insufficient_balance ctx w src dst amount hallow
          (Nat.not_le.mp hsub)
        simp [worldAfter, hrun] at hdec
    · have hrun := transferFrom_reverts_on_insufficient_allowance ctx w src dst amount
        (Nat.not_le.mp hallow)
      simp [worldAfter, hrun] at hdec

theorem burn_auth : NoUnauthorizedDecreaseFn spec Inv claim Auth .burn := by
  intro amount ctx w a _hInv hdec
  rw [Auth_burn]
  by_cases hs : ctx.sender = a
  · exact hs
  · by_cases hsub : amount ≤ w.self.balances ctx.sender
    · by_cases hsupply : amount ≤ w.self.totalSupply
      · have hrun := burn_ok ctx w amount hsub hsupply
        simp [worldAfter, hrun] at hdec
        simp [claim, burnPost, debit_other _ (Ne.symm hs)] at hdec
      · have hrun := burn_reverts_on_insufficient_supply ctx w amount hsub
          (Nat.not_le.mp hsupply)
        simp [worldAfter, hrun] at hdec
    · have hrun := burn_reverts_on_insufficient_balance ctx w amount (Nat.not_le.mp hsub)
      simp [worldAfter, hrun] at hdec

theorem mint_auth : NoUnauthorizedDecreaseFn spec Inv claim Auth .mint := by
  intro ⟨dst, amount⟩ ctx w a _hInv hdec
  by_cases howner : ctx.sender = w.self.owner
  · by_cases hsupply : (w.self.totalSupply + amount).raw < wordBound
    · by_cases hadd : (w.self.balances dst + amount).raw < wordBound
      · have hrun := mint_ok ctx w dst amount howner hsupply hadd
        simp [worldAfter, hrun] at hdec
        simp [claim, mintPost] at hdec
        by_cases ht : a = dst
        · subst ht
          simp [credit] at hdec
        · simp [credit_other _ ht] at hdec
      · have hrun := mint_reverts_on_balance_overflow ctx w dst amount howner hsupply
          (Nat.not_lt.mp hadd)
        simp [worldAfter, hrun] at hdec
    · have hrun := mint_reverts_on_overflow ctx w dst amount howner (Nat.not_lt.mp hsupply)
      simp [worldAfter, hrun] at hdec
  · have hrun := mint_reverts_for_non_owner ctx w dst amount howner
    simp [worldAfter, hrun] at hdec

theorem approve_auth : NoUnauthorizedDecreaseFn spec Inv claim Auth .approve := by
  intro ⟨spender, amount⟩ ctx w a _hInv hdec
  have ⟨w', hrun, hb⟩ := approve_preserves_balances ctx w spender amount
  simp [worldAfter, hrun] at hdec
  simp [claim, hb] at hdec

theorem balanceOf_auth : NoUnauthorizedDecreaseFn spec Inv claim Auth .balanceOf := by
  intro who ctx w a _hInv hdec
  unfold worldAfter at hdec
  rw [balanceOf_returns_stored_balance ctx w who] at hdec
  exact (Nat.lt_irrefl _ hdec).elim

theorem allowance_auth : NoUnauthorizedDecreaseFn spec Inv claim Auth .allowance := by
  intro ⟨owner, spender⟩ ctx w a _hInv hdec
  unfold worldAfter at hdec
  rw [allowance_returns_stored ctx w owner spender] at hdec
  exact (Nat.lt_irrefl _ hdec).elim

theorem totalSupply_auth : NoUnauthorizedDecreaseFn spec Inv claim Auth .totalSupply := by
  intro u ctx w a _hInv hdec
  unfold worldAfter at hdec
  rw [totalSupply_returns_stored ctx w] at hdec
  exact (Nat.lt_irrefl _ hdec).elim

theorem token_no_unauth : NoUnauthorizedDecrease spec Inv claim Auth :=
  NoUnauthorizedDecrease.of_fns fun fn =>
    match fn with
    | .transfer => transfer_auth
    | .transferFrom => transferFrom_auth
    | .burn => burn_auth
    | .mint => mint_auth
    | .approve => approve_auth
    | .balanceOf => balanceOf_auth
    | .allowance => allowance_auth
    | .totalSupply => totalSupply_auth

/-! ### (b) Conservation -/

theorem transfer_conservesFn : ConservesFn spec Inv claim inflow .transfer := by
  intro ⟨dst, amount⟩ ctx w _hInv
  refine ⟨({ctx.sender, dst} : Finset Address), ?frame, ?sum⟩
  · intro a ha
    have hst : a ≠ ctx.sender ∧ a ≠ dst := by
      simpa [Finset.mem_insert, Finset.mem_singleton] using ha
    by_cases hsub : amount ≤ w.self.balances ctx.sender
    · by_cases hadd : (debit w.self.balances ctx.sender amount dst + amount).raw < wordBound
      · have ⟨w', hrun, hb⟩ :=
          transfer_preserves_other_balances ctx w dst amount a hst.1 hst.2 hsub hadd
        simp [worldAfter, hrun]; simp [claim, hb]
      · have hrun := transfer_reverts_on_overflow ctx w dst amount hsub (Nat.not_lt.mp hadd)
        simp [worldAfter, hrun]
    · have hrun := transfer_reverts_on_insufficient_balance ctx w dst amount (Nat.not_le.mp hsub)
      simp [worldAfter, hrun]
  · by_cases hsub : amount ≤ w.self.balances ctx.sender
    · by_cases hadd : (debit w.self.balances ctx.sender amount dst + amount).raw < wordBound
      · by_cases hne : ctx.sender = dst
        · subst hne
          have hbound : (w.self.balances ctx.sender).raw < wordBound := by
            have hle : amount.raw ≤ (w.self.balances ctx.sender).raw := hsub
            simp [debit, Function.update_self, Amount.raw_add, Amount.raw_sub] at hadd
            rw [Nat.sub_add_cancel hle] at hadd
            exact hadd
          have ⟨w', hrun, hb⟩ := transfer_self_transfer_is_noop ctx w amount hsub hbound
          simp [worldAfter, hrun]; simp [claim, hb, inflow, Call.ofCtx]
        · have hne' : ctx.sender ≠ dst := hne
          have hadd' : (w.self.balances dst + amount).raw < wordBound := by
            simpa [debit_other _ hne'.symm] using hadd
          have hrun := transfer_ok ctx w dst amount hsub
            (by simpa [debit_other _ hne'.symm] using hadd')
          have hcons := Proof.transfer_conserves ctx w dst amount hrun
          simp [worldAfter, hrun]
          rw [Finset.sum_pair hne', Finset.sum_pair hne']
          simp [claim, inflow, Call.ofCtx]
          exact le_of_eq (by simpa [Amount.raw_add] using congrArg Amount.raw hcons)
      · have hrun := transfer_reverts_on_overflow ctx w dst amount hsub (Nat.not_lt.mp hadd)
        simp [worldAfter, hrun]
    · have hrun := transfer_reverts_on_insufficient_balance ctx w dst amount (Nat.not_le.mp hsub)
      simp [worldAfter, hrun]

theorem transferFrom_conservesFn : ConservesFn spec Inv claim inflow .transferFrom := by
  intro ⟨src, dst, amount⟩ ctx w _hInv
  refine ⟨({src, dst} : Finset Address), ?frame, ?sum⟩
  · intro a ha
    have hst : a ≠ src ∧ a ≠ dst := by
      simpa [Finset.mem_insert, Finset.mem_singleton] using ha
    by_cases hallow : amount ≤ w.self.allowances src ctx.sender
    · by_cases hsub : amount ≤ w.self.balances src
      · by_cases hadd : (debit w.self.balances src amount dst + amount).raw < wordBound
        · have ⟨w', hrun, hb⟩ :=
            transferFrom_preserves_other_balances ctx w src dst amount a hst.1 hst.2
              hallow hsub hadd
          simp [worldAfter, hrun]; simp [claim, hb]
        · have hrun := transferFrom_reverts_on_overflow ctx w src dst amount hallow hsub
            (Nat.not_lt.mp hadd)
          simp [worldAfter, hrun]
      · have hrun := transferFrom_reverts_on_insufficient_balance ctx w src dst amount hallow
          (Nat.not_le.mp hsub)
        simp [worldAfter, hrun]
    · have hrun := transferFrom_reverts_on_insufficient_allowance ctx w src dst amount
        (Nat.not_le.mp hallow)
      simp [worldAfter, hrun]
  · by_cases hallow : amount ≤ w.self.allowances src ctx.sender
    · by_cases hsub : amount ≤ w.self.balances src
      · by_cases hadd : (debit w.self.balances src amount dst + amount).raw < wordBound
        · by_cases hne : src = dst
          · subst hne
            have hbound : (w.self.balances src).raw < wordBound := by
              have hle : amount.raw ≤ (w.self.balances src).raw := hsub
              simp [debit, Function.update_self, Amount.raw_add, Amount.raw_sub] at hadd
              rw [Nat.sub_add_cancel hle] at hadd
              exact hadd
            have ⟨w', hrun, hb⟩ :=
              transferFrom_self_transfer_is_noop ctx w src amount hallow hsub hbound
            simp [worldAfter, hrun]; simp [claim, hb, inflow, Call.ofCtx]
          · have hne' : src ≠ dst := hne
            have hadd' : (w.self.balances dst + amount).raw < wordBound := by
              simpa [debit_other _ hne'.symm] using hadd
            have ⟨w', hrun, hcons⟩ :=
              transferFrom_conserves ctx w src dst amount hne' hallow hsub hadd'
            simp [worldAfter, hrun]
            rw [Finset.sum_pair hne', Finset.sum_pair hne']
            simp [claim, inflow, Call.ofCtx]
            exact le_of_eq (by simpa [Amount.raw_add] using congrArg Amount.raw hcons)
        · have hrun := transferFrom_reverts_on_overflow ctx w src dst amount hallow hsub
            (Nat.not_lt.mp hadd)
          simp [worldAfter, hrun]
      · have hrun := transferFrom_reverts_on_insufficient_balance ctx w src dst amount hallow
          (Nat.not_le.mp hsub)
        simp [worldAfter, hrun]
    · have hrun := transferFrom_reverts_on_insufficient_allowance ctx w src dst amount
        (Nat.not_le.mp hallow)
      simp [worldAfter, hrun]

theorem mint_conservesFn : ConservesFn spec Inv claim inflow .mint := by
  intro ⟨dst, amount⟩ ctx w _hInv
  refine ⟨({dst} : Finset Address), ?frame, ?sum⟩
  · intro a ha
    have hat : a ≠ dst := by simpa [Finset.mem_singleton] using ha
    by_cases howner : ctx.sender = w.self.owner
    · by_cases hsupply : (w.self.totalSupply + amount).raw < wordBound
      · by_cases hadd : (w.self.balances dst + amount).raw < wordBound
        · have ⟨w', hrun, hb⟩ :=
            mint_preserves_other_balances ctx w dst amount a hat howner hsupply hadd
          simp [worldAfter, hrun]; simp [claim, hb]
        · have hrun := mint_reverts_on_balance_overflow ctx w dst amount howner hsupply
            (Nat.not_lt.mp hadd)
          simp [worldAfter, hrun]
      · have hrun := mint_reverts_on_overflow ctx w dst amount howner (Nat.not_lt.mp hsupply)
        simp [worldAfter, hrun]
    · have hrun := mint_reverts_for_non_owner ctx w dst amount howner
      simp [worldAfter, hrun]
  · by_cases howner : ctx.sender = w.self.owner
    · by_cases hsupply : (w.self.totalSupply + amount).raw < wordBound
      · by_cases hadd : (w.self.balances dst + amount).raw < wordBound
        · have hrun := mint_ok ctx w dst amount howner hsupply hadd
          simp [worldAfter, hrun]
          simp [claim, mintPost, credit, inflow, Call.ofCtx, Call.toCtx, hrun]
        · have hrun := mint_reverts_on_balance_overflow ctx w dst amount howner hsupply
            (Nat.not_lt.mp hadd)
          simp [worldAfter, hrun]
      · have hrun := mint_reverts_on_overflow ctx w dst amount howner (Nat.not_lt.mp hsupply)
        simp [worldAfter, hrun]
    · have hrun := mint_reverts_for_non_owner ctx w dst amount howner
      simp [worldAfter, hrun]

theorem burn_conservesFn : ConservesFn spec Inv claim inflow .burn := by
  intro amount ctx w _hInv
  refine ⟨({ctx.sender} : Finset Address), ?frame, ?sum⟩
  · intro a ha
    have hs : a ≠ ctx.sender := by simpa [Finset.mem_singleton] using ha
    by_cases hsub : amount ≤ w.self.balances ctx.sender
    · by_cases hsupply : amount ≤ w.self.totalSupply
      · have ⟨w', hrun, hb⟩ :=
          burn_preserves_other_balances ctx w amount a hs hsub hsupply
        simp [worldAfter, hrun]; simp [claim, hb]
      · have hrun := burn_reverts_on_insufficient_supply ctx w amount hsub
          (Nat.not_le.mp hsupply)
        simp [worldAfter, hrun]
    · have hrun := burn_reverts_on_insufficient_balance ctx w amount (Nat.not_le.mp hsub)
      simp [worldAfter, hrun]
  · by_cases hsub : amount ≤ w.self.balances ctx.sender
    · by_cases hsupply : amount ≤ w.self.totalSupply
      · have hrun := burn_ok ctx w amount hsub hsupply
        simp [worldAfter, hrun]
        simp [claim, burnPost, debit, inflow, Call.ofCtx]
      · have hrun := burn_reverts_on_insufficient_supply ctx w amount hsub
          (Nat.not_le.mp hsupply)
        simp [worldAfter, hrun]
    · have hrun := burn_reverts_on_insufficient_balance ctx w amount (Nat.not_le.mp hsub)
      simp [worldAfter, hrun]

theorem approve_conservesFn : ConservesFn spec Inv claim inflow .approve := by
  intro ⟨spender, amount⟩ ctx w _hInv
  refine ⟨∅, ?_, ?_⟩
  · intro a _
    have ⟨w', hrun, hb⟩ := approve_preserves_balances ctx w spender amount
    simp [worldAfter, hrun]; simp [claim, hb]
  · have ⟨_, hrun, _⟩ := approve_preserves_balances ctx w spender amount
    simp [worldAfter, hrun]

theorem balanceOf_conservesFn : ConservesFn spec Inv claim inflow .balanceOf := by
  intro who ctx w _hInv
  refine ⟨∅, ?_, ?_⟩
  · intro a _
    unfold worldAfter
    rw [balanceOf_returns_stored_balance ctx w who]
  · unfold worldAfter
    rw [balanceOf_returns_stored_balance ctx w who]
    simp [claim, inflow, Call.ofCtx]

theorem allowance_conservesFn : ConservesFn spec Inv claim inflow .allowance := by
  intro ⟨owner, spender⟩ ctx w _hInv
  refine ⟨∅, ?_, ?_⟩
  · intro a _
    unfold worldAfter
    rw [allowance_returns_stored ctx w owner spender]
  · unfold worldAfter
    rw [allowance_returns_stored ctx w owner spender]
    simp [claim, inflow, Call.ofCtx]

theorem totalSupply_conservesFn : ConservesFn spec Inv claim inflow .totalSupply := by
  intro u ctx w _hInv
  refine ⟨∅, ?_, ?_⟩
  · intro a _
    unfold worldAfter
    rw [totalSupply_returns_stored ctx w]
  · unfold worldAfter
    rw [totalSupply_returns_stored ctx w]
    simp [claim, inflow, Call.ofCtx]

theorem token_conservation : Conservation spec Inv claim inflow :=
  Conservation.of_fns fun fn =>
    match fn with
    | .transfer => transfer_conservesFn
    | .transferFrom => transferFrom_conservesFn
    | .burn => burn_conservesFn
    | .mint => mint_conservesFn
    | .approve => approve_conservesFn
    | .balanceOf => balanceOf_conservesFn
    | .allowance => allowance_conservesFn
    | .totalSupply => totalSupply_conservesFn

/-! ### (c) Invariant preservation -/

theorem transfer_preserves_inv : PreservesInvFn spec Inv .transfer := by
  intro ⟨dst, amount⟩ ctx w hInv
  by_cases hsub : amount ≤ w.self.balances ctx.sender
  · by_cases hadd : (debit w.self.balances ctx.sender amount dst + amount).raw < wordBound
    · have hrun := transfer_ok ctx w dst amount hsub hadd
      simp [worldAfter, hrun]
      exact inv_of_transferPost w.self ctx.sender dst amount hInv hsub
    · have hrun := transfer_reverts_on_overflow ctx w dst amount hsub (Nat.not_lt.mp hadd)
      simp [worldAfter, hrun]
      exact hInv
  · have hrun := transfer_reverts_on_insufficient_balance ctx w dst amount (Nat.not_le.mp hsub)
    simp [worldAfter, hrun]
    exact hInv

theorem transferFrom_preserves_inv : PreservesInvFn spec Inv .transferFrom := by
  intro ⟨src, dst, amount⟩ ctx w hInv
  by_cases hallow : amount ≤ w.self.allowances src ctx.sender
  · by_cases hsub : amount ≤ w.self.balances src
    · by_cases hadd : (debit w.self.balances src amount dst + amount).raw < wordBound
      · have hrun := transferFrom_ok ctx w src dst amount hallow hsub hadd
        simp [worldAfter, hrun]
        exact inv_of_transferPost w.self src dst amount hInv hsub
      · have hrun := transferFrom_reverts_on_overflow ctx w src dst amount hallow hsub
          (Nat.not_lt.mp hadd)
        simp [worldAfter, hrun]
        exact hInv
    · have hrun := transferFrom_reverts_on_insufficient_balance ctx w src dst amount hallow
        (Nat.not_le.mp hsub)
      simp [worldAfter, hrun]
      exact hInv
  · have hrun := transferFrom_reverts_on_insufficient_allowance ctx w src dst amount
      (Nat.not_le.mp hallow)
    simp [worldAfter, hrun]
    exact hInv

theorem mint_preserves_inv : PreservesInvFn spec Inv .mint := by
  intro ⟨dst, amount⟩ ctx w hInv
  by_cases howner : ctx.sender = w.self.owner
  · by_cases hsupply : (w.self.totalSupply + amount).raw < wordBound
    · by_cases hadd : (w.self.balances dst + amount).raw < wordBound
      · have hrun := mint_ok ctx w dst amount howner hsupply hadd
        simp [worldAfter, hrun]
        exact inv_of_mintPost w.self dst amount hInv
      · have hrun := mint_reverts_on_balance_overflow ctx w dst amount howner hsupply
          (Nat.not_lt.mp hadd)
        simp [worldAfter, hrun]
        exact hInv
    · have hrun := mint_reverts_on_overflow ctx w dst amount howner (Nat.not_lt.mp hsupply)
      simp [worldAfter, hrun]
      exact hInv
  · have hrun := mint_reverts_for_non_owner ctx w dst amount howner
    simp [worldAfter, hrun]
    exact hInv

theorem burn_preserves_inv : PreservesInvFn spec Inv .burn := by
  intro amount ctx w hInv
  by_cases hsub : amount ≤ w.self.balances ctx.sender
  · by_cases hsupply : amount ≤ w.self.totalSupply
    · have hrun := burn_ok ctx w amount hsub hsupply
      simp [worldAfter, hrun]
      exact inv_of_burnPost w.self ctx.sender amount hInv hsub
    · have hrun := burn_reverts_on_insufficient_supply ctx w amount hsub (Nat.not_le.mp hsupply)
      simp [worldAfter, hrun]
      exact hInv
  · have hrun := burn_reverts_on_insufficient_balance ctx w amount (Nat.not_le.mp hsub)
    simp [worldAfter, hrun]
    exact hInv

theorem approve_preserves_inv : PreservesInvFn spec Inv .approve := by
  intro ⟨spender, amount⟩ ctx w hInv
  have hrun := approve_ok ctx w spender amount
  simp [worldAfter, hrun]
  obtain ⟨H, h0, hsum⟩ := hInv
  exact ⟨H, fun a ha => h0 a ha, hsum⟩

theorem balanceOf_preserves_inv : PreservesInvFn spec Inv .balanceOf := by
  intro who ctx w hInv
  unfold worldAfter
  rw [balanceOf_returns_stored_balance ctx w who]
  exact hInv

theorem allowance_preserves_inv : PreservesInvFn spec Inv .allowance := by
  intro ⟨owner, spender⟩ ctx w hInv
  unfold worldAfter
  rw [allowance_returns_stored ctx w owner spender]
  exact hInv

theorem totalSupply_preserves_inv : PreservesInvFn spec Inv .totalSupply := by
  intro u ctx w hInv
  unfold worldAfter
  rw [totalSupply_returns_stored ctx w]
  exact hInv

theorem token_preserves_inv : PreservesInv spec Inv :=
  PreservesInv.of_fns fun fn =>
    match fn with
    | .transfer => transfer_preserves_inv
    | .transferFrom => transferFrom_preserves_inv
    | .burn => burn_preserves_inv
    | .mint => mint_preserves_inv
    | .approve => approve_preserves_inv
    | .balanceOf => balanceOf_preserves_inv
    | .allowance => allowance_preserves_inv
    | .totalSupply => totalSupply_preserves_inv

/-- Environment steps are a no-op on `Inv` (`X := Unit`). -/
theorem token_inv_rely : PreservesInvEnv spec Inv (fun _ _ => True) := by
  intro w x' hw _
  exact hw

/-- Deployment from empty balances establishes `Inv`. -/
theorem «constructor_inv» (owner : Address) (supply : Amount tokenAsset) (ctx : Ctx)
    (w : World Storage Unit Event)
    (hempty : ∀ a, w.self.balances a = 0) :
    Inv (worldAfter (Token.constructor owner supply) ctx w) := by
  have hrun := ctor_ok ctx w owner supply
  simp [worldAfter, hrun, Inv, InvStorage]
  refine ⟨{owner}, ?_, ?_⟩
  · intro a ha
    have hne : a ≠ owner := by simpa [Finset.mem_singleton] using ha
    simp [ctorPost, Function.update_of_ne hne, hempty]
  ·     simp [ctorPost, Finset.sum_singleton, Function.update_self]

namespace Proof

theorem token_no_unauthorized_extraction
    (tr : List (Step spec)) (w : World Storage Unit Event) (a : Address)
    (hw : Inv w) (hR : RelyAlong (fun _ _ => True) tr w)
    (hA : NoAuthAlong Auth a tr w) :
    claim a w.self ≤ claim a (run tr w).self :=
  no_unauthorized_extraction token_no_unauth token_preserves_inv token_inv_rely
    tr w a hw hR hA

theorem token_solvent (self : Address) (tr : List (Step spec)) (w : World Storage Unit Event)
    (hW : Wf self tr) (hR : RelyAlong (fun _ _ => True) tr w) (h : Inv w) :
    Inv (run tr w) :=
  inv_run token_preserves_inv token_inv_rely h tr hW hR

end Proof

end Token
