import Lsc.Security.Trace

namespace Lsc.Security

variable {S X E ε : Type}

/-- Protocol invariant on the whole world (storage, ghosts, logs). -/
abbrev Inv (S X E : Type) := World S X E → Prop

/-- Between our calls, the ghost record evolves under `rely`. -/
def RelyAlong {C : Spec S X E ε} (rely : X → X → Prop) : List (Step C) → World S X E → Prop
  | [], _ => True
  | .call c :: tr, w => RelyAlong rely tr (step (.call c) w)
  | .env x' :: tr, w => rely w.ext x' ∧ RelyAlong rely tr { w with ext := x' }

/-- Every call of `C` preserves `Inv` when it holds in the pre-world. -/
def PreservesInv (C : Spec S X E ε) (Inv : World S X E → Prop) : Prop :=
  ∀ (c : Call C) (w : World S X E), Inv w → Inv (step (.call c) w)

/-- Per-entrypoint form generated by `lsc_contract` (unpacked args, no `Call`). -/
def PreservesInvFn (C : Spec S X E ε) (Inv : World S X E → Prop) (fn : C.Fn) : Prop :=
  ∀ (args : C.Args fn) (ctx : Ctx) (w : World S X E),
    Inv w → Inv (worldAfter (C.exec fn args) ctx w)

theorem PreservesInv.of_fns {C : Spec S X E ε} {Inv : World S X E → Prop}
    (h : ∀ fn, PreservesInvFn C Inv fn) : PreservesInv C Inv := by
  intro c w hc
  simpa [step] using h c.fn c.args c.toCtx w hc

/-- `Inv` is preserved by a `rely`-conformant environment step. -/
def PreservesInvEnv (_C : Spec S X E ε) (Inv : World S X E → Prop)
    (rely : X → X → Prop) : Prop :=
  ∀ (w : World S X E) (x' : X), Inv w → rely w.ext x' → Inv { w with ext := x' }

theorem inv_run {C : Spec S X E ε} {Inv : World S X E → Prop} {rely : X → X → Prop}
    (hC : PreservesInv C Inv) (hE : PreservesInvEnv C Inv rely)
    {w : World S X E} (hw : Inv w) {self : Address} (tr : List (Step C))
    (hW : Wf self tr) (hR : RelyAlong rely tr w) :
    Inv (run tr w) := by
  induction tr generalizing w with
  | nil => simpa using hw
  | cons s tr ih =>
    match s with
    | .call c =>
      have htl : Wf self tr := hW.2.2
      exact ih (hC c w hw) htl hR
    | .env x' =>
      have ⟨hr, htl⟩ := hR
      exact ih (hE w x' hw hr) hW htl

end Lsc.Security
