import Lsc.Security.Trace

namespace Lsc.Security

variable {S E ε : Type} {C : Spec S E ε}

/-- Protocol invariant on storage. Logs/`ext` are ignored. -/
abbrev Inv (S : Type) := S → Prop

/-- Every call of `C` preserves `Inv` when it holds in the pre-state. -/
def PreservesInv (C : Spec S E ε) (Inv : S → Prop) : Prop :=
  ∀ (c : Call C) (w : World S E), Inv w.self → Inv (step c w).self

/-- Per-entrypoint form generated by `lsc_contract` (unpacked args, no `Call`). -/
def PreservesInvFn (C : Spec S E ε) (Inv : S → Prop) (fn : C.Fn) : Prop :=
  ∀ (args : C.Args fn) (ctx : Ctx) (w : World S E),
    Inv w.self → Inv (worldAfter (C.exec fn args) ctx w).self

theorem PreservesInv.of_fns {Inv : S → Prop}
    (h : ∀ fn, PreservesInvFn C Inv fn) : PreservesInv C Inv := by
  intro c w hc
  simpa [step] using h c.fn c.args c.toCtx w hc

theorem inv_run {Inv : S → Prop} (h : PreservesInv C Inv)
    {w : World S E} (hw : Inv w.self) (tr : List (Call C)) :
    Inv (run tr w).self := by
  induction tr generalizing w with
  | nil => simpa using hw
  | cons _ _ ih => exact ih (h _ _ hw)

end Lsc.Security
