import LscV2.Prelude
import LscV2.Compile.Yul
import LscV2.Compile.Bytecode

/-!
Counter contract written with the Lean-first DSL (`TxM` builder +
`deriving ContractStorage/ContractError/ContractEvent` + `derive_contract_dsl`).
Storage/error/event boilerplate — `getField`/`setField`/`resolveError`/
`buildEvent`/the `ContractDSL` instance/the `ContractErrors` instance — is
entirely generated by the three `deriving` clauses + `derive_contract_dsl`
below, rather than hand-written.

Target shape: `docs/spec_idea_2/reference/COUNTER.md`. The compile section
at the bottom (`counterDef`/`compileConfig`/`counterBytecodeHex`/
`counterDeployHex`) confirms the compile pipeline
(`Compile.configFromContract`/`contractToBytecodeHex`/`deployToBytecodeHex`)
consumes a `TxM`-built `Stmt` exactly like a hand-written one.
-/

open LscV2 LscV2.Compile

namespace Counter

structure CounterStorage where
  number : Wei := Wei.mkNat 0
  paused : Bool := false
  owner : Address := 0
  deriving Repr, LscV2.Deriving.ContractStorage

instance : Inhabited CounterStorage where
  default := {}

inductive CounterError where
  | Paused
  | NotOwner
  | Overflow
  deriving Repr, DecidableEq, LscV2.Deriving.ContractError

inductive CounterEvent where
  | Incremented (n : Wei)
  | Paused
  | Unpaused
  deriving Repr, DecidableEq, LscV2.Deriving.ContractEvent

derive_contract_dsl CounterStorage CounterError CounterEvent

-- `deriving ContractStorage/ContractError/ContractEvent` (above) generates
-- `CounterStorage.getField`/`setField`, `CounterError.resolveError`, and
-- `CounterEvent.buildEvent` as plain `match`-based `def`s (see
-- `LscV2.Deriving` for the generated shape). They need explicit `@[simp]`
-- tags for the same reason a hand-written equivalent would:
-- `Stmt.evalWith`'s simp set (`Lang/Eval.lean`) only unfolds as far as
-- `dsl.getField`/`dsl.setField`/`dsl.resolveErr`/`dsl.buildEvent` (the
-- `ContractDSL` *projections*); without lemmas relating those projections
-- back to the concrete derived defs above, `simp` cannot see through the
-- (reducible but not `@[simp]`) `ContractDSL` instance that
-- `derive_contract_dsl` assembled to actually evaluate a `getField`/
-- `setField`/... call. Marking the generated defs themselves `@[simp]`
-- (so their own `match` equations fire) plus relating the class
-- projections to them is what lets `CounterTheorem.lean`'s proofs use
-- plain `simp`.
attribute [simp] CounterStorage.getField CounterStorage.setField
  CounterError.resolveError CounterEvent.buildEvent

@[simp] theorem counterDsl_getField (t : Ty) (f : Ident) (s : CounterStorage) :
    @ContractDSL.getField CounterStorage CounterEvent CounterError _ _ t f s =
      CounterStorage.getField t f s := rfl

@[simp] theorem counterDsl_setField (t : Ty) (f : Ident) (v : Val t) (s : CounterStorage) :
    @ContractDSL.setField CounterStorage CounterEvent CounterError _ _ t f v s =
      CounterStorage.setField t f v s := rfl

@[simp] theorem counterDsl_resolveErr (name : Ident) :
    @ContractDSL.resolveErr CounterStorage CounterEvent CounterError _ _ name =
      CounterError.resolveError name := rfl

@[simp] theorem counterDsl_buildEvent (name : Ident) (vals : List (Sigma Val)) :
    @ContractDSL.buildEvent CounterStorage CounterEvent CounterError _ _ name vals =
      CounterEvent.buildEvent name vals := rfl

@[simp] theorem counterError_arith_overflow :
    @ContractErrors.arith CounterError _ ArithError.Overflow = CounterError.Overflow := rfl

abbrev CounterM := ContractM CounterStorage CounterEvent CounterError

def incrementTxM : TxM Unit := do
  require !(bool σ.paused) else revert Paused
  let n ← letWei "n" (wei σ.number +? 1)
  setWei "number" n
  emit "Incremented" [⟨Ty.wei, n⟩]

def incrementAst : Stmt := TxM.run incrementTxM

def increment : CounterM Unit := Stmt.eval incrementAst

-- `t` is given explicitly here (rather than relying on `===`'s implicit-`t`
-- inference) because `msg.sender : CoreExpr (txFieldTy .caller)` and
-- `addr σ.owner : CoreExpr Ty.address` are only *defeq*, not syntactically
-- equal types; letting `t` be inferred from the first (`msg.sender`)
-- argument leaves it stuck as the unreduced `txFieldTy TxField.caller`
-- term, which then fails to syntactically match the literal `Ty.address`
-- pattern in `CounterStorage.getField`'s `@[simp]` match equations — see
-- `CounterTheorem.lean`'s module docstring for the proof-side symptom this
-- caused before this annotation was added.
def pauseTxM : TxM Unit := do
  require (@CoreExpr.eqAuto Ty.address msg.sender (addr σ.owner)) else revert NotOwner
  require !(bool σ.paused) else revert Paused
  setBool "paused" (CoreExpr.lit Ty.bool (.bool true))
  emit "Paused" []

def pauseAst : Stmt := TxM.run pauseTxM

def pause : CounterM Unit := Stmt.eval pauseAst

def unpauseTxM : TxM Unit := do
  require (@CoreExpr.eqAuto Ty.address msg.sender (addr σ.owner)) else revert NotOwner
  require (bool σ.paused) else revert Paused
  setBool "paused" (CoreExpr.lit Ty.bool (.bool false))
  emit "Unpaused" []

def unpauseAst : Stmt := TxM.run unpauseTxM

def unpause : CounterM Unit := Stmt.eval unpauseAst

/-! ## Compilation: `ContractDef` + Yul/bytecode emission -/

def counterFn (name : Ident) (body : Stmt) : FunctionDef where
  name := name
  kind := .external
  params := []
  retTy := .unit
  body := body

def counterDef : ContractDef where
  name := "Counter"
  storage :=
    [("number", .wei, none), ("paused", .bool, some ⟨.bool, CoreExpr.lit Ty.bool (.bool false)⟩),
     ("owner", .address, none)]
  errors := ["Paused", "NotOwner", "Overflow"]
  events := [("Incremented", [("n", .wei)]), ("Paused", []), ("Unpaused", [])]
  functions :=
    [counterFn "increment" incrementAst, counterFn "pause" pauseAst,
     counterFn "unpause" unpauseAst]
  interfaces := []
  -- Set owner = msg.sender (deployer) at construction time so pause/unpause work.
  constructor := some (Stmt.storageSet "owner" ⟨Ty.address, CoreExpr.txField .caller⟩)

/-- Compile layout for Yul / bytecode emission. -/
def stubEventTopic0 : Ident → Option Nat
  | "Incremented" => some 0x20d8a6f5a693f9d1d627a598e8820f7a55ee74c183aa8f1a30e8d4e8dd9a8d84
  | name => some name.hash.toNat

def compileConfig : Config :=
  Compile.configFromContract counterDef stubEventTopic0

def incrementYul : String :=
  match Compile.stmtToYul compileConfig incrementAst with
  | .ok yul => yul
  | .error _ => ""

def counterBytecodeHex : String :=
  match Compile.contractToBytecodeHex counterDef stubEventTopic0 with
  | .ok hex => hex
  | .error _ => ""

/-- Full deploy transaction payload (constructor sets owner = deployer, then
    returns runtime bytecode via CODECOPY + RETURN). -/
def counterDeployHex : String :=
  match Compile.deployToBytecodeHex counterDef stubEventTopic0 with
  | .ok hex => hex
  | .error _ => ""

-- Smoke-checks
#check Counter.CounterStorage
#check Counter.CounterError
#check Counter.CounterEvent
#check Counter.CounterM
#check Counter.increment
#check Counter.pause
#check Counter.unpause
#check Counter.counterDef
#check Counter.counterBytecodeHex
#check Counter.counterDeployHex

end Counter
